// @generated by AI
package com.smarthealth.controller.admin;

import com.smarthealth.common.Result;
import com.smarthealth.dto.response.WeightRecordResponse;
import com.smarthealth.dto.response.PlanHistoryResponse;
import com.smarthealth.dto.response.UserResponse;
import com.smarthealth.entity.User;
import com.smarthealth.mapper.UserMapper;
import com.smarthealth.service.PlanService;
import com.smarthealth.service.WeightService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.RequiredArgsConstructor;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

@Tag(name = "管理员用户管理", description = "管理员后台用户管理")
@RestController
@RequestMapping("/api/v1/admin/users")
@RequiredArgsConstructor
@PreAuthorize("hasRole('ADMIN')")
public class AdminUserController {

    private final UserMapper userMapper;
    private final WeightService weightService;
    private final PlanService planService;

    @Operation(summary = "查询用户列表")
    @GetMapping
    public Result<Map<String, Object>> listUsers(@RequestParam(defaultValue = "1") int page,
                                                  @RequestParam(defaultValue = "10") int size,
                                                  @RequestParam(required = false) String keyword) {
        List<User> users = userMapper.findAll();
        List<UserResponse> records = users.stream()
                .map(u -> new UserResponse(u.getId(), u.getUsername(), u.getRole(),
                        u.getStatus(), u.getVipExpireTime() != null ? u.getVipExpireTime().toString() : null))
                .collect(Collectors.toList());
        return Result.success(Map.of("total", (long) users.size(), "records", records));
    }

    @Operation(summary = "查询用户详情")
    @GetMapping("/{id}")
    public Result<UserResponse> getUserDetail(@PathVariable Long id) {
        User user = userMapper.findById(id);
        if (user == null) {
            return Result.error(404, "用户不存在");
        }
        return Result.success(new UserResponse(user.getId(), user.getUsername(), user.getRole(),
                user.getStatus(), user.getVipExpireTime() != null ? user.getVipExpireTime().toString() : null));
    }

    @Operation(summary = "启用用户")
    @PutMapping("/{id}/enable")
    public Result<Void> enableUser(@PathVariable Long id) {
        userMapper.updateStatus(id, 1);
        return Result.success("启用成功", null);
    }

    @Operation(summary = "禁用用户")
    @PutMapping("/{id}/disable")
    public Result<Void> disableUser(@PathVariable Long id) {
        userMapper.updateStatus(id, 0);
        return Result.success("禁用成功", null);
    }

    @Operation(summary = "查询用户体重记录")
    @GetMapping("/{id}/weights")
    public Result<List<WeightRecordResponse>> getUserWeights(@PathVariable Long id) {
        return Result.success(weightService.getHistory(id));
    }

    @Operation(summary = "查询用户计划记录")
    @GetMapping("/{id}/plans")
    public Result<List<PlanHistoryResponse>> getUserPlans(@PathVariable Long id) {
        return Result.success(planService.getHistory(id));
    }
}
