// @generated by AI
package com.smarthealth.controller.admin;

import com.smarthealth.common.Result;
import com.smarthealth.dto.request.CreateKnowledgeRequest;
import com.smarthealth.dto.response.KnowledgeResponse;
import com.smarthealth.service.RagService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import jakarta.validation.constraints.Max;
import jakarta.validation.constraints.Min;
import lombok.RequiredArgsConstructor;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

@Tag(name = "知识库管理", description = "管理员健康知识库管理")
@RestController
@RequestMapping("/api/v1/admin/knowledge")
@RequiredArgsConstructor
@PreAuthorize("hasRole('ADMIN')")
public class KnowledgeController {

    private final RagService ragService;

    @Operation(summary = "新增健康知识")
    @PostMapping
    public Result<Map<String, String>> createKnowledge(@Valid @RequestBody CreateKnowledgeRequest request) {
        String knowledgeId = ragService.addKnowledge(request.getDocument(), request.toMetadataMap());
        return Result.success("新增成功", Map.of("knowledgeId", knowledgeId));
    }

    @Operation(summary = "修改健康知识")
    @PutMapping("/{id}")
    public Result<Void> updateKnowledge(@PathVariable String id,
                                         @Valid @RequestBody CreateKnowledgeRequest request) {
        ragService.updateKnowledge(id, request.getDocument(), request.toMetadataMap());
        return Result.success("修改成功", null);
    }

    @Operation(summary = "删除健康知识")
    @DeleteMapping("/{id}")
    public Result<Void> deleteKnowledge(@PathVariable String id) {
        ragService.deleteKnowledge(id);
        return Result.success("删除成功", null);
    }

    @Operation(summary = "查询健康知识列表（分页）")
    @GetMapping("/list")
    public Result<Map<String, Object>> listKnowledge(
            @RequestParam(required = false) String category,
            @RequestParam(required = false) String keyword,
            @RequestParam(required = false) String status,
            @RequestParam(required = false) String level,
            @RequestParam(defaultValue = "1") @Min(1) int page,
            @RequestParam(defaultValue = "10") @Min(1) @Max(100) int size) {
        List<Map<String, Object>> items = ragService.listKnowledge(category, keyword, status, level);
        List<KnowledgeResponse> allRecords = items.stream()
                .map(m -> new KnowledgeResponse(
                        (String) m.get("id"),
                        (String) m.get("document"),
                        (Map<String, Object>) m.get("metadata")))
                .collect(Collectors.toList());
        int total = allRecords.size();
        int fromIndex = Math.min((page - 1) * size, total);
        int toIndex = Math.min(fromIndex + size, total);
        List<KnowledgeResponse> records = allRecords.subList(fromIndex, toIndex);
        return Result.success(Map.of("total", total, "records", records));
    }

    @Operation(summary = "启用健康知识")
    @PutMapping("/{id}/enable")
    public Result<Void> enableKnowledge(@PathVariable String id) {
        ragService.updateKnowledge(id, null, Map.of("status", "enabled"));
        return Result.success("启用成功", null);
    }

    @Operation(summary = "禁用健康知识")
    @PutMapping("/{id}/disable")
    public Result<Void> disableKnowledge(@PathVariable String id) {
        ragService.updateKnowledge(id, null, Map.of("status", "disabled"));
        return Result.success("禁用成功", null);
    }
}
