// @generated by AI
package com.smarthealth.dto.response;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Data;

@Data
@AllArgsConstructor
@Schema(description = "AI 配置响应（Key 已脱敏）")
public class AiConfigResponse {

    @JsonProperty("provider")
    @Schema(description = "AI 提供方", example = "CUSTOM")
    private String provider;

    @JsonProperty("customProvider")
    @Schema(description = "自定义 AI 厂商", example = "deepseek")
    private String customProvider;

    @JsonProperty("apiKey")
    @Schema(description = "API Key（已脱敏）", example = "sk-****abcd")
    private String apiKey;

    @JsonProperty("apiUrl")
    @Schema(description = "API 地址", example = "https://api.deepseek.com/v1/chat/completions")
    private String apiUrl;

    @JsonProperty("model")
    @Schema(description = "模型名称", example = "deepseek-chat")
    private String model;
}
