// @generated by AI
package com.smarthealth.dto.response;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Data;
import java.util.List;

@Data
@AllArgsConstructor
@Schema(description = "智能问答响应")
public class ChatResponse {

    @JsonProperty("answer")
    @Schema(description = "AI 回答", example = "减脂期间晚餐建议控制总热量...")
    private String answer;

    @JsonProperty("references")
    @Schema(description = "参考知识标题")
    private List<ReferenceItem> references;

    @Data
    @AllArgsConstructor
    @Schema(description = "参考知识项")
    public static class ReferenceItem {

        @JsonProperty("title")
        private String title;

        @JsonProperty("category")
        private String category;
    }
}
