// @generated by AI
package com.smarthealth.dto.response;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Data;

@Data
@AllArgsConstructor
@Schema(description = "今日生成次数响应")
public class GenerateCountResponse {

    @JsonProperty("used")
    @Schema(description = "今日已用次数", example = "1")
    private Integer used;

    @JsonProperty("limit")
    @Schema(description = "今日限制次数", example = "2")
    private Integer limit;

    @JsonProperty("remaining")
    @Schema(description = "今日剩余次数", example = "1")
    private Integer remaining;
}
