// @generated by AI
package com.smarthealth.dto.response;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Data;
import java.util.Map;

@Data
@AllArgsConstructor
@Schema(description = "健康知识响应")
public class KnowledgeResponse {

    @JsonProperty("id")
    @Schema(description = "知识 ID", example = "knowledge_fat_loss_001")
    private String id;

    @JsonProperty("document")
    @Schema(description = "知识正文", example = "减脂期间应控制总热量摄入。")
    private String document;

    @JsonProperty("metadata")
    @Schema(description = "知识元数据")
    private Map<String, Object> metadata;
}
