// @generated by AI
package com.smarthealth.dto.response;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Data;
import java.util.Map;

@Data
@AllArgsConstructor
@Schema(description = "健康知识响应")
public class KnowledgeResponse {

    @JsonProperty("id")
    private String id;

    @JsonProperty("document")
    private String document;

    @JsonProperty("metadata")
    private Map<String, Object> metadata;
}
