// @generated by AI
package com.smarthealth.dto.response;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Data;
import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

@Data
@AllArgsConstructor
@Schema(description = "计划详情（含 AI 生成内容）")
public class PlanDetailResponse {

    @JsonProperty("id")
    private Long id;

    @JsonProperty("planType")
    private String planType;

    @JsonProperty("planLevel")
    private String planLevel;

    @JsonProperty("planContent")
    private Map<String, Object> planContent;

    @JsonProperty("trendSummary")
    private String trendSummary;

    @JsonProperty("references")
    private List<ReferenceItem> references;

    @JsonProperty("createTime")
    private LocalDateTime createTime;

    @Data
    @AllArgsConstructor
    @Schema(description = "参考知识项")
    public static class ReferenceItem {

        @JsonProperty("title")
        private String title;

        @JsonProperty("category")
        private String category;
    }
}
