// @generated by AI
package com.smarthealth.dto.response;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Data;
import java.time.LocalDateTime;

@Data
@AllArgsConstructor
@Schema(description = "计划历史响应")
public class PlanHistoryResponse {

    @JsonProperty("id")
    private Long id;

    @JsonProperty("planType")
    private String planType;

    @JsonProperty("planLevel")
    private String planLevel;

    @JsonProperty("trendSummary")
    private String trendSummary;

    @JsonProperty("createTime")
    private LocalDateTime createTime;
}
