// @generated by AI
package com.smarthealth.dto.response;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Data;
import java.math.BigDecimal;

@Data
@AllArgsConstructor
@Schema(description = "健康档案响应")
public class ProfileResponse {

    @JsonProperty("id")
    @Schema(description = "档案 ID", example = "1")
    private Long id;

    @JsonProperty("age")
    @Schema(description = "年龄", example = "22")
    private Integer age;

    @JsonProperty("gender")
    @Schema(description = "性别", example = "男")
    private String gender;

    @JsonProperty("height")
    @Schema(description = "身高(cm)", example = "175.0")
    private BigDecimal height;

    @JsonProperty("weight")
    @Schema(description = "体重(kg)", example = "80.0")
    private BigDecimal weight;

    @JsonProperty("activityLevel")
    @Schema(description = "活动水平", example = "较低")
    private String activityLevel;

    @JsonProperty("dietPreference")
    @Schema(description = "饮食偏好", example = "少油少糖")
    private String dietPreference;

    @JsonProperty("goal")
    @Schema(description = "健康目标", example = "减脂")
    private String goal;
}
