// @generated by AI
package com.smarthealth.dto.response;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Data;
import java.math.BigDecimal;
import java.time.LocalDate;

@Data
@AllArgsConstructor
@Schema(description = "体重记录响应")
public class WeightRecordResponse {

    @JsonProperty("id")
    @Schema(description = "记录 ID", example = "1")
    private Long id;

    @JsonProperty("weight")
    @Schema(description = "体重(kg)", example = "79.5")
    private BigDecimal weight;

    @JsonProperty("recordDate")
    @Schema(description = "记录日期", example = "2026-06-08")
    private LocalDate recordDate;
}
