// @generated by AI
package com.smarthealth.dto.response;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.v3.oas.annotations.media.Schema;
import lombok.AllArgsConstructor;
import lombok.Data;
import java.math.BigDecimal;
import java.util.List;

@Data
@AllArgsConstructor
@Schema(description = "体重趋势响应")
public class WeightTrendResponse {

    @JsonProperty("dates")
    @Schema(description = "日期列表", example = "[\"06-02\",\"06-03\"]")
    private List<String> dates;

    @JsonProperty("values")
    @Schema(description = "体重值列表", example = "[65.2,65.0]")
    private List<BigDecimal> values;
}
