// @generated by AI
package com.smarthealth.service;

import com.smarthealth.common.BusinessException;
import com.smarthealth.common.ResultCode;
import com.smarthealth.entity.UserAiConfig;
import com.smarthealth.mapper.UserAiConfigMapper;
import com.smarthealth.util.EncryptionUtil;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

@Service
@RequiredArgsConstructor
public class AiRoutingService {

    private final UserAiConfigMapper configMapper;
    private final DeepSeekAiService deepSeekAiService;
    private final ClaudeAiService claudeAiService;
    private final OllamaAiService ollamaAiService;
    private final EncryptionUtil encryptionUtil;

    public String chat(Long userId, String role, String systemPrompt, String userPrompt) {
        UserAiConfig config = configMapper.findByUserId(userId);

        if (config != null && "CUSTOM".equals(config.getProvider())) {
            if (config.getApiKey() == null) {
                throw new BusinessException(ResultCode.BAD_REQUEST, "自定义 API Key 未配置");
            }
            String decryptedKey = encryptionUtil.decrypt(config.getApiKey());
            String customProvider = config.getCustomProvider() != null ? config.getCustomProvider() : "deepseek";
            if ("claude".equals(customProvider)) {
                return claudeAiService.chat(
                        decryptedKey,
                        config.getApiUrl(),
                        config.getModel(),
                        systemPrompt,
                        userPrompt
                );
            }
            return deepSeekAiService.chat(
                    decryptedKey,
                    config.getApiUrl(),
                    config.getModel(),
                    systemPrompt,
                    userPrompt
            );
        }

        if ("VIP".equals(role) && config != null && "LOCAL".equals(config.getProvider())) {
            return ollamaAiService.chat(systemPrompt, userPrompt);
        }

        return deepSeekAiService.chat(systemPrompt, userPrompt);
    }
}
