// @generated by AI
package com.smarthealth.service;

import jakarta.annotation.PostConstruct;
import lombok.RequiredArgsConstructor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Map;

@Service
@RequiredArgsConstructor
public class ChromaInitService {

    private static final Logger log = LoggerFactory.getLogger(ChromaInitService.class);

    private final RagService ragService;

    @PostConstruct
    public void init() {
        try {
            ragService.ensureCollectionExists();
            log.info("Chroma collection ensured: smart_health_knowledge");

            long count = ragService.count();
            log.info("Chroma knowledge count: {}", count);

            if (count == 0) {
                log.info("Seeding default health knowledge...");
                seedDefaultKnowledge();
                log.info("Default health knowledge seeded successfully");
            } else {
                log.info("Knowledge base already populated, skipping seed");
            }
        } catch (Exception e) {
            log.warn("Chroma initialization skipped: {}", e.getMessage());
        }
    }

    private void seedDefaultKnowledge() {
        List<SeedKnowledge> seeds = List.of(
                new SeedKnowledge("减脂期间建议每天摄入热量控制在1500-1800大卡，保证蛋白质摄入量占总热量的30%以上，碳水化合物占40-45%，脂肪占20-25%。", "减脂热量控制原则", "饮食", "all"),
                new SeedKnowledge("每周进行3-5次有氧运动，每次30-45分钟，可有效提高心肺功能和燃脂效率。推荐跑步、游泳、骑行等运动。", "有氧运动建议", "运动", "all"),
                new SeedKnowledge("增肌期间每日蛋白质摄入量建议为每公斤体重1.6-2.2克，碳水每公斤体重4-6克，脂肪每公斤体重0.8-1克。", "增肌营养建议", "饮食", "all"),
                new SeedKnowledge("建议每天保持7-8小时的睡眠时间，睡眠不足会影响代谢和食欲激素的平衡，可能导致体重增加。", "睡眠健康建议", "作息", "all"),
                new SeedKnowledge("力量训练每周2-4次，每次训练后至少休息48小时再训练同一肌群。训练动作应包括复合动作和孤立动作。", "力量训练频率建议", "运动", "all"),
                new SeedKnowledge("每日饮水量建议为体重的30-40毫升/公斤，运动日需额外补充水分。少量多次饮水更有利于身体吸收。", "每日饮水建议", "饮食", "all"),
                new SeedKnowledge("HIIT（高强度间歇训练）每次15-30分钟，每周2-3次，燃脂效果优于匀速有氧。适合有一定运动基础的人群。", "HIIT训练建议", "运动", "all"),
                new SeedKnowledge("早餐建议在起床后1小时内进食，包含优质蛋白和复合碳水。晚餐建议在睡前3小时完成，避免高油高糖食物。", "进餐时间建议", "饮食", "all"),
                new SeedKnowledge("久坐人群每45-60分钟起身活动5分钟，可改善血液循环、减少腰椎压力、提高代谢水平。", "久坐健康提醒", "作息", "all"),
                new SeedKnowledge("运动前应进行5-10分钟动态热身，运动后应进行10-15分钟静态拉伸，可有效减少运动损伤和肌肉酸痛。", "运动热身与拉伸", "运动", "all"),
                new SeedKnowledge("膳食纤维每日推荐摄入量25-35克，可促进肠道健康、增加饱腹感、延缓血糖上升。推荐全谷物、豆类、蔬菜。", "膳食纤维建议", "饮食", "all"),
                new SeedKnowledge("保持规律的作息时间，固定起床和入睡时间有助于稳定生物钟，改善睡眠质量和新陈代谢。", "规律作息建议", "作息", "all")
        );

        for (SeedKnowledge seed : seeds) {
            ragService.addKnowledge(seed.document, Map.of(
                    "title", seed.title,
                    "category", seed.category,
                    "status", "enabled",
                    "level", seed.level
            ));
        }
    }

    private record SeedKnowledge(String document, String title, String category, String level) {}
}
