// @generated by AI
package com.smarthealth.service;

import com.smarthealth.common.BusinessException;
import com.smarthealth.common.ResultCode;
import com.smarthealth.config.DeepSeekConfig;
import lombok.RequiredArgsConstructor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

@Service
@RequiredArgsConstructor
public class DeepSeekAiService implements AiChatService {

    private static final Logger log = LoggerFactory.getLogger(DeepSeekAiService.class);

    private final DeepSeekConfig deepSeekConfig;
    private final RestTemplate deepSeekRestTemplate;

    @Override
    public String chat(String systemPrompt, String userPrompt) {
        return chat(deepSeekConfig.getApiKey(), deepSeekConfig.getUrl(),
                deepSeekConfig.getModel(), systemPrompt, userPrompt);
    }

    public String chat(String apiKey, String apiUrl, String model,
                        String systemPrompt, String userPrompt) {
        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);
        headers.setBearerAuth(apiKey);

        Map<String, Object> requestBody = new LinkedHashMap<>();
        requestBody.put("model", model);
        requestBody.put("messages", List.of(
                Map.of("role", "system", "content", systemPrompt),
                Map.of("role", "user", "content", userPrompt)
        ));
        if (systemPrompt.contains("JSON") || systemPrompt.contains("json")
                || userPrompt.contains("JSON") || userPrompt.contains("json")) {
            requestBody.put("response_format", Map.of("type", "json_object"));
        }

        HttpEntity<Map<String, Object>> request = new HttpEntity<>(requestBody, headers);

        try {
            ResponseEntity<Map> response = deepSeekRestTemplate.postForEntity(
                    apiUrl, request, Map.class);
            Map body = response.getBody();
            if (body == null || !body.containsKey("choices")) {
                throw new BusinessException(ResultCode.AI_SERVICE_ERROR, "DeepSeek 返回格式异常");
            }
            List<Map<String, Object>> choices = (List<Map<String, Object>>) body.get("choices");
            if (choices.isEmpty()) {
                throw new BusinessException(ResultCode.AI_SERVICE_ERROR, "DeepSeek 返回空结果");
            }
            Map<String, Object> message = (Map<String, Object>) choices.get(0).get("message");
            return (String) message.get("content");
        } catch (Exception e) {
            log.error("AI 服务调用失败: apiUrl={}", apiUrl, e);
            throw new BusinessException(ResultCode.AI_SERVICE_ERROR, "AI 服务异常，请稍后重试");
        }
    }
}
