// @generated by AI
package com.smarthealth.service;

import com.smarthealth.config.ChromaConfig;
import com.smarthealth.config.DeepSeekConfig;
import com.smarthealth.dto.response.HealthResponse;
import lombok.RequiredArgsConstructor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import javax.sql.DataSource;
import java.sql.Connection;

@Service
@RequiredArgsConstructor
public class HealthService {

    private static final Logger log = LoggerFactory.getLogger(HealthService.class);

    private final DataSource dataSource;
    private final ChromaConfig chromaConfig;
    private final DeepSeekConfig deepSeekConfig;
    private final RestTemplate restTemplate;

    public HealthResponse check() {
        return new HealthResponse(
                checkMysql(),
                checkChroma(),
                checkDeepSeek()
        );
    }

    private String checkMysql() {
        try (Connection conn = dataSource.getConnection()) {
            if (conn.isValid(2)) {
                return "UP";
            }
            return "DOWN";
        } catch (Exception e) {
            log.warn("MySQL health check failed: {}", e.getMessage());
            return "DOWN";
        }
    }

    private String checkChroma() {
        try {
            String url = chromaConfig.getUrl() + "/api/v1/heartbeat";
            restTemplate.getForEntity(url, String.class);
            return "UP";
        } catch (Exception e) {
            log.warn("Chroma health check failed: {}", e.getMessage());
            return "DOWN";
        }
    }

    private String checkDeepSeek() {
        if (deepSeekConfig.getApiKey() != null && !deepSeekConfig.getApiKey().isBlank()
                && !deepSeekConfig.getApiKey().startsWith("${")) {
            return "UP";
        }
        return "DOWN";
    }
}
