// @generated by AI
package com.smarthealth.service;

import com.smarthealth.common.BusinessException;
import com.smarthealth.common.ResultCode;
import com.smarthealth.config.OllamaConfig;
import lombok.RequiredArgsConstructor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import java.util.List;
import java.util.Map;

@Service
@RequiredArgsConstructor
public class OllamaAiService implements AiChatService {

    private static final Logger log = LoggerFactory.getLogger(OllamaAiService.class);

    private final OllamaConfig ollamaConfig;
    private final RestTemplate ollamaRestTemplate;

    @Override
    public String chat(String systemPrompt, String userPrompt) {
        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);

        Map<String, Object> requestBody = Map.of(
                "model", ollamaConfig.getModel(),
                "messages", List.of(
                        Map.of("role", "system", "content", systemPrompt),
                        Map.of("role", "user", "content", userPrompt)
                ),
                "stream", false
        );

        HttpEntity<Map<String, Object>> request = new HttpEntity<>(requestBody, headers);

        try {
            ResponseEntity<Map> response = ollamaRestTemplate.postForEntity(
                    ollamaConfig.getUrl() + "/api/chat", request, Map.class);
            Map body = response.getBody();
            if (body == null || !body.containsKey("message")) {
                throw new BusinessException(ResultCode.AI_SERVICE_ERROR, "Ollama 返回格式异常");
            }
            Map<String, Object> message = (Map<String, Object>) body.get("message");
            return (String) message.get("content");
        } catch (Exception e) {
            log.error("Ollama 服务调用失败", e);
            throw new BusinessException(ResultCode.AI_SERVICE_ERROR, "AI 服务异常，请稍后重试");
        }
    }
}
