// @generated by AI
package com.smarthealth.service;

import com.smarthealth.common.BusinessException;
import com.smarthealth.common.ResultCode;
import com.smarthealth.dto.response.GenerateCountResponse;
import com.smarthealth.dto.response.PlanDetailResponse;
import com.smarthealth.dto.response.PlanHistoryResponse;
import com.smarthealth.entity.*;
import com.smarthealth.mapper.*;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;
import lombok.RequiredArgsConstructor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.*;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
public class PlanService {

    private final PlanMapper planMapper;
    private final PlanGenerateRecordMapper generateRecordMapper;
    private final ProfileMapper profileMapper;
    private final WeightService weightService;
    private final DeepSeekService deepSeekService;
    private final RagService ragService;
    private final ObjectMapper objectMapper;

    private static final Logger log = LoggerFactory.getLogger(PlanService.class);
    private static final int USER_DAILY_LIMIT = 2;
    private static final int VIP_DAILY_LIMIT = 5;

    @Transactional(rollbackFor = Exception.class)
    public PlanDetailResponse generatePlan(Long userId, String role) {
        checkGenerateLimit(userId, role);

        HealthProfile profile = profileMapper.findByUserId(userId);
        if (profile == null) {
            throw new BusinessException(ResultCode.NOT_FOUND, "请先填写健康档案");
        }

        String trendSummary = weightService.analyzeTrend(userId);

        List<Map<String, Object>> ragResults;
        try {
            ragResults = ragService.query(
                    profile.getGoal() + " " + profile.getDietPreference(),
                    5, role);
        } catch (Exception e) {
            log.warn("Chroma unavailable, falling back to AI-only generation", e);
            ragResults = List.of();
        }

        String userPrompt = buildUserPrompt(profile, trendSummary, ragResults);
        String systemPrompt = buildSystemPrompt(role);

        String aiResponse = deepSeekService.chat(systemPrompt, userPrompt);

        Map<String, Object> planContent;
        try {
            planContent = objectMapper.readValue(aiResponse,
                    new TypeReference<Map<String, Object>>() {});
        } catch (Exception e) {
            planContent = Map.of("raw", aiResponse);
        }

        String planLevel = "VIP".equals(role) ? "VIP" : "BASIC";

        Plan plan = new Plan();
        plan.setUserId(userId);
        plan.setPlanType("COMBINED");
        plan.setPlanLevel(planLevel);
        plan.setPlanContent(aiResponse);
        plan.setTrendSummary(trendSummary);
        planMapper.insert(plan);

        incrementGenerateCount(userId);

        List<PlanDetailResponse.ReferenceItem> references = ragResults.stream()
                .map(r -> {
                    Map<String, Object> meta = (Map<String, Object>) r.get("metadata");
                    return new PlanDetailResponse.ReferenceItem(
                            (String) meta.get("title"),
                            (String) meta.get("category"));
                })
                .collect(Collectors.toList());

        return toDetailResponse(plan, planContent, references);
    }

    public List<PlanHistoryResponse> getHistory(Long userId) {
        return planMapper.findByUserId(userId).stream()
                .map(p -> new PlanHistoryResponse(
                        p.getId(), p.getPlanType(), p.getPlanLevel(),
                        p.getTrendSummary(), p.getCreateTime()))
                .collect(Collectors.toList());
    }

    public PlanDetailResponse getDetail(Long userId, String role, Long planId) {
        Plan plan = planMapper.findById(planId);
        if (plan == null) {
            throw new BusinessException(ResultCode.NOT_FOUND, "计划不存在");
        }
        if (!"ADMIN".equals(role) && !plan.getUserId().equals(userId)) {
            throw new BusinessException(ResultCode.FORBIDDEN, "无权限查看该计划");
        }

        Map<String, Object> planContent;
        try {
            planContent = objectMapper.readValue(plan.getPlanContent(),
                    new TypeReference<Map<String, Object>>() {});
        } catch (Exception e) {
            planContent = Map.of("raw", plan.getPlanContent());
        }

        return toDetailResponse(plan, planContent, List.of());
    }

    public GenerateCountResponse getGenerateCount(Long userId, String role) {
        int limit = "VIP".equals(role) ? VIP_DAILY_LIMIT : USER_DAILY_LIMIT;
        PlanGenerateRecord record = generateRecordMapper.findByUserIdAndDate(userId, LocalDate.now());
        int used = record != null ? record.getGenerateCount() : 0;
        return new GenerateCountResponse(used, limit, Math.max(0, limit - used));
    }

    private void checkGenerateLimit(Long userId, String role) {
        int limit = "VIP".equals(role) ? VIP_DAILY_LIMIT : USER_DAILY_LIMIT;
        PlanGenerateRecord record = generateRecordMapper.findByUserIdAndDate(userId, LocalDate.now());
        int used = record != null ? record.getGenerateCount() : 0;
        if (used >= limit) {
            throw new BusinessException(ResultCode.FORBIDDEN, "今日 AI 计划生成次数已用完");
        }
    }

    private void incrementGenerateCount(Long userId) {
        PlanGenerateRecord record = generateRecordMapper.findByUserIdAndDate(userId, LocalDate.now());
        if (record == null) {
            record = new PlanGenerateRecord();
            record.setUserId(userId);
            record.setGenerateDate(LocalDate.now());
            record.setGenerateCount(1);
            generateRecordMapper.insert(record);
        } else {
            generateRecordMapper.updateCount(record.getId(), record.getGenerateCount() + 1);
        }
    }

    private String buildSystemPrompt(String role) {
        boolean isVip = "VIP".equals(role);
        StringBuilder sb = new StringBuilder();
        sb.append("你是一个专业的健康管理助手。请根据用户信息生成一周饮食和运动计划。");
        sb.append("必须以 JSON 格式返回，包含以下字段：");
        sb.append("\"dietPlan\": 包含每日早餐、午餐、晚餐、加餐建议的数组；");
        sb.append("\"exercisePlan\": 包含每日运动类型、时长、频率、强度的数组。");
        if (isVip) {
            sb.append("额外返回 \"vipDetail\" 字段，包含：");
            sb.append("\"calorieEstimate\"（每餐热量估算）、");
            sb.append("\"nutritionRatio\"（蛋白质/碳水/脂肪比例建议）、");
            sb.append("\"exerciseIntensity\"（训练强度分级）、");
            sb.append("\"weeklyReview\"（每周复盘建议）。");
        }
        sb.append("返回内容仅供健康管理参考，不能替代专业医疗建议。");
        return sb.toString();
    }

    private String buildUserPrompt(HealthProfile profile, String trendSummary,
                                    List<Map<String, Object>> ragResults) {
        StringBuilder sb = new StringBuilder();
        sb.append(String.format("用户信息：\n年龄：%d\n性别：%s\n身高：%.1fcm\n当前体重：%.1fkg\n"
                        + "活动水平：%s\n饮食偏好：%s\n健康目标：%s\n\n体重趋势：%s\n\n",
                profile.getAge(), profile.getGender(),
                profile.getHeight(), profile.getWeight(),
                profile.getActivityLevel(),
                profile.getDietPreference() != null ? profile.getDietPreference() : "无特殊",
                profile.getGoal(), trendSummary));

        if (ragResults != null && !ragResults.isEmpty()) {
            sb.append("参考以下健康知识生成计划：\n");
            for (Map<String, Object> result : ragResults) {
                sb.append("- ").append(result.get("document")).append("\n");
            }
            sb.append("\n");
        }

        sb.append("请根据以上信息生成一周健康计划。");
        return sb.toString();
    }

    private PlanDetailResponse toDetailResponse(Plan plan, Map<String, Object> planContent,
                                                  List<PlanDetailResponse.ReferenceItem> references) {
        return new PlanDetailResponse(
                plan.getId(), plan.getPlanType(), plan.getPlanLevel(),
                planContent, plan.getTrendSummary(), references, plan.getCreateTime());
    }
}
