// @generated by AI
package com.smarthealth.service;

import com.smarthealth.common.BusinessException;
import com.smarthealth.common.ResultCode;
import com.smarthealth.dto.request.SaveProfileRequest;
import com.smarthealth.dto.response.ProfileResponse;
import com.smarthealth.entity.HealthProfile;
import com.smarthealth.mapper.ProfileMapper;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;

@Service
@RequiredArgsConstructor
public class ProfileService {

    private final ProfileMapper profileMapper;

    public ProfileResponse getProfile(Long userId) {
        HealthProfile profile = profileMapper.findByUserId(userId);
        if (profile == null) {
            throw new BusinessException(ResultCode.NOT_FOUND, "健康档案不存在");
        }
        return toResponse(profile);
    }

    public void saveProfile(Long userId, SaveProfileRequest request) {
        HealthProfile existing = profileMapper.findByUserId(userId);
        if (existing != null) {
            throw new BusinessException(ResultCode.CONFLICT, "健康档案已存在，请使用修改接口");
        }

        HealthProfile profile = toEntity(userId, request);
        profileMapper.insert(profile);
    }

    public void updateProfile(Long userId, SaveProfileRequest request) {
        HealthProfile existing = profileMapper.findByUserId(userId);
        if (existing == null) {
            throw new BusinessException(ResultCode.NOT_FOUND, "健康档案不存在");
        }

        HealthProfile profile = toEntity(userId, request);
        profile.setId(existing.getId());
        profileMapper.update(profile);
    }

    private ProfileResponse toResponse(HealthProfile profile) {
        return new ProfileResponse(
                profile.getId(), profile.getAge(), profile.getGender(),
                profile.getHeight(), profile.getWeight(),
                profile.getActivityLevel(), profile.getDietPreference(),
                profile.getGoal()
        );
    }

    private HealthProfile toEntity(Long userId, SaveProfileRequest request) {
        HealthProfile profile = new HealthProfile();
        profile.setUserId(userId);
        profile.setAge(request.getAge());
        profile.setGender(request.getGender());
        profile.setHeight(request.getHeight());
        profile.setWeight(request.getWeight());
        profile.setActivityLevel(request.getActivityLevel());
        profile.setDietPreference(request.getDietPreference());
        profile.setGoal(request.getGoal());
        return profile;
    }
}
