// @generated by AI
package com.smarthealth.service;

import com.smarthealth.common.BusinessException;
import com.smarthealth.common.ResultCode;
import com.smarthealth.config.ChromaConfig;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import java.util.*;
import java.util.concurrent.atomic.AtomicReference;

@Service
@RequiredArgsConstructor
public class RagService {

    private final ChromaConfig chromaConfig;
    private final RestTemplate restTemplate;
    private final AtomicReference<String> collectionUuid = new AtomicReference<>();

    private String getCollectionUuid() {
        String uuid = collectionUuid.get();
        if (uuid == null) {
            String listUrl = chromaConfig.getUrl() + "/api/v1/collections";
            try {
                List<Map<String, Object>> collections = restTemplate.getForEntity(listUrl, List.class).getBody();
                if (collections != null) {
                    for (Map<String, Object> col : collections) {
                        if (chromaConfig.getCollectionName().equals(col.get("name"))) {
                            uuid = (String) col.get("id");
                            collectionUuid.set(uuid);
                            break;
                        }
                    }
                }
            } catch (Exception e) {
                throw new BusinessException(ResultCode.CHROMA_ERROR, "Chroma UUID 获取失败: " + e.getMessage());
            }
            if (uuid == null) {
                throw new BusinessException(ResultCode.CHROMA_ERROR, "Chroma 集合未找到: " + chromaConfig.getCollectionName());
            }
        }
        return uuid;
    }

    private void refreshCollectionUuid() {
        collectionUuid.set(null);
        getCollectionUuid();
    }

    private String dataPath() {
        return "/api/v1/collections/" + getCollectionUuid();
    }

    public String addKnowledge(String document, Map<String, String> metadata) {
        String url = chromaConfig.getUrl() + dataPath() + "/add";
        String knowledgeId = "knowledge_" + UUID.randomUUID().toString().substring(0, 8);
        Map<String, Object> body = new HashMap<>();
        body.put("documents", List.of(document));
        body.put("metadatas", List.of(metadata));
        body.put("ids", List.of(knowledgeId));
        try {
            restTemplate.postForEntity(url, new HttpEntity<>(body, jsonHeaders()), Boolean.class);
            return knowledgeId;
        } catch (Exception e) {
            throw new BusinessException(ResultCode.CHROMA_ERROR, "Chroma 写入失败: " + e.getMessage());
        }
    }

    public void updateKnowledge(String knowledgeId, String document, Map<String, String> metadata) {
        String url = chromaConfig.getUrl() + dataPath() + "/update";
        Map<String, Object> body = new HashMap<>();
        body.put("ids", List.of(knowledgeId));
        if (document != null) body.put("documents", List.of(document));
        if (metadata != null) body.put("metadatas", List.of(metadata));
        try {
            restTemplate.postForEntity(url, new HttpEntity<>(body, jsonHeaders()), Object.class);
        } catch (Exception e) {
            throw new BusinessException(ResultCode.CHROMA_ERROR, "Chroma 更新失败: " + e.getMessage());
        }
    }

    public void deleteKnowledge(String knowledgeId) {
        String url = chromaConfig.getUrl() + dataPath() + "/delete";
        Map<String, Object> body = new HashMap<>();
        body.put("ids", List.of(knowledgeId));
        try {
            restTemplate.postForEntity(url, new HttpEntity<>(body, jsonHeaders()), Object.class);
        } catch (Exception e) {
            throw new BusinessException(ResultCode.CHROMA_ERROR, "Chroma 删除失败: " + e.getMessage());
        }
    }

    public List<Map<String, Object>> query(String queryText, int nResults, String role) {
        String url = chromaConfig.getUrl() + dataPath() + "/get";
        Map<String, Object> body = new HashMap<>();
        Map<String, Object> where = new HashMap<>();
        where.put("status", "enabled");
        if ("USER".equals(role)) {
            where.put("$or", List.of(Map.of("level", "basic"), Map.of("level", "all")));
        }
        body.put("where", where);
        body.put("where_document", Map.of("$contains", queryText));
        body.put("limit", nResults);

        try {
            var response = restTemplate.postForEntity(url, new HttpEntity<>(body, jsonHeaders()), Map.class);
            Map<String, Object> responseBody = response.getBody();
            if (responseBody == null) return List.of();

            List<Object> documents = (List<Object>) responseBody.get("documents");
            List<Object> metadatas = (List<Object>) responseBody.get("metadatas");
            List<Object> ids = (List<Object>) responseBody.get("ids");

            List<Map<String, Object>> results = new ArrayList<>();
            if (ids != null) {
                for (int i = 0; i < ids.size(); i++) {
                    Map<String, Object> item = new HashMap<>();
                    item.put("id", ids.get(i));
                    if (documents != null && i < documents.size()) item.put("document", documents.get(i));
                    if (metadatas != null && i < metadatas.size()) item.put("metadata", metadatas.get(i));
                    results.add(item);
                }
            }
            return results;
        } catch (Exception e) {
            throw new BusinessException(ResultCode.CHROMA_ERROR, "Chroma 检索失败: " + e.getMessage());
        }
    }

    public void ensureCollectionExists() {
        String checkUrl = chromaConfig.getUrl() + "/api/v1/collections/" + chromaConfig.getCollectionName();
        try {
            restTemplate.getForEntity(checkUrl, Map.class);
        } catch (Exception e) {
            String createUrl = chromaConfig.getUrl() + "/api/v1/collections";
            Map<String, Object> body = new HashMap<>();
            body.put("name", chromaConfig.getCollectionName());
            try {
                restTemplate.postForEntity(createUrl, new HttpEntity<>(body, jsonHeaders()), Map.class);
            } catch (Exception ex) {
                throw new BusinessException(ResultCode.CHROMA_ERROR, "Chroma 集合创建失败: " + ex.getMessage());
            }
        }
        refreshCollectionUuid();
    }

    public long count() {
        String url = chromaConfig.getUrl() + dataPath() + "/count";
        try {
            var response = restTemplate.getForEntity(url, Long.class);
            return response.getBody() != null ? response.getBody() : 0;
        } catch (Exception e) {
            return 0;
        }
    }

    public List<Map<String, Object>> listKnowledge(String category, String keyword, String status, String level) {
        String url = chromaConfig.getUrl() + dataPath() + "/get";
        try {
            Map<String, Object> body = new HashMap<>();
            Map<String, Object> where = new HashMap<>();
            List<Map<String, Object>> conditions = new ArrayList<>();
            if (category != null && !category.isEmpty()) {
                conditions.add(Map.of("category", category));
            }
            if (status != null && !status.isEmpty()) {
                conditions.add(Map.of("status", status));
            }
            if (level != null && !level.isEmpty()) {
                conditions.add(Map.of("level", level));
            }
            if (!conditions.isEmpty()) {
                if (conditions.size() == 1) {
                    where.putAll(conditions.get(0));
                } else {
                    where.put("$and", conditions);
                }
                body.put("where", where);
            }
            if (keyword != null && !keyword.isEmpty()) {
                body.put("where_document", Map.of("$contains", keyword));
            }

            var response = restTemplate.postForEntity(url, new HttpEntity<>(body, jsonHeaders()), Map.class);
            Map<String, Object> responseBody = response.getBody();
            if (responseBody == null) return List.of();

            List<Object> ids = (List<Object>) responseBody.get("ids");
            List<Object> documents = (List<Object>) responseBody.get("documents");
            List<Object> metadatas = (List<Object>) responseBody.get("metadatas");

            List<Map<String, Object>> results = new ArrayList<>();
            if (ids != null) {
                for (int i = 0; i < ids.size(); i++) {
                    Map<String, Object> item = new HashMap<>();
                    item.put("id", ids.get(i));
                    if (documents != null && i < documents.size()) item.put("document", documents.get(i));
                    if (metadatas != null && i < metadatas.size()) item.put("metadata", metadatas.get(i));
                    results.add(item);
                }
            }
            return results;
        } catch (Exception e) {
            throw new BusinessException(ResultCode.CHROMA_ERROR, "Chroma 查询失败: " + e.getMessage());
        }
    }

    private HttpHeaders jsonHeaders() {
        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);
        return headers;
    }
}
