// @generated by AI
package com.smarthealth.service;

import com.smarthealth.common.BusinessException;
import com.smarthealth.common.ResultCode;
import com.smarthealth.config.ChromaConfig;
import lombok.RequiredArgsConstructor;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.stereotype.Service;
import org.springframework.web.client.RestTemplate;

import java.util.*;

@Service
@RequiredArgsConstructor
public class RagService {

    private final ChromaConfig chromaConfig;
    private final RestTemplate restTemplate;

    public void addKnowledge(String document, Map<String, String> metadata) {
        String url = chromaConfig.getUrl() + "/api/v1/collections/" + chromaConfig.getCollectionName() + "/add";
        Map<String, Object> body = new HashMap<>();
        body.put("documents", List.of(document));
        body.put("metadatas", List.of(metadata));
        body.put("ids", List.of(UUID.randomUUID().toString()));
        try {
            restTemplate.postForEntity(url, new HttpEntity<>(body, jsonHeaders()), Map.class);
        } catch (Exception e) {
            throw new BusinessException(ResultCode.CHROMA_ERROR, "Chroma 写入失败: " + e.getMessage());
        }
    }

    public void updateKnowledge(String knowledgeId, String document, Map<String, String> metadata) {
        String url = chromaConfig.getUrl() + "/api/v1/collections/" + chromaConfig.getCollectionName() + "/update";
        Map<String, Object> body = new HashMap<>();
        body.put("ids", List.of(knowledgeId));
        if (document != null) body.put("documents", List.of(document));
        if (metadata != null) body.put("metadatas", List.of(metadata));
        try {
            restTemplate.postForEntity(url, new HttpEntity<>(body, jsonHeaders()), Map.class);
        } catch (Exception e) {
            throw new BusinessException(ResultCode.CHROMA_ERROR, "Chroma 更新失败: " + e.getMessage());
        }
    }

    public void deleteKnowledge(String knowledgeId) {
        String url = chromaConfig.getUrl() + "/api/v1/collections/" + chromaConfig.getCollectionName() + "/delete";
        Map<String, Object> body = new HashMap<>();
        body.put("ids", List.of(knowledgeId));
        try {
            restTemplate.postForEntity(url, new HttpEntity<>(body, jsonHeaders()), Map.class);
        } catch (Exception e) {
            throw new BusinessException(ResultCode.CHROMA_ERROR, "Chroma 删除失败: " + e.getMessage());
        }
    }

    public List<Map<String, Object>> query(String queryText, int nResults, String role) {
        String url = chromaConfig.getUrl() + "/api/v1/collections/" + chromaConfig.getCollectionName() + "/query";
        Map<String, Object> body = new HashMap<>();
        body.put("query_texts", List.of(queryText));
        body.put("n_results", nResults);
        body.put("where", Map.of("status", "enabled"));

        if ("USER".equals(role)) {
            body.put("where_document", Map.of("$or", List.of(
                    Map.of("level", "basic"), Map.of("level", "all")
            )));
        }

        try {
            var response = restTemplate.postForEntity(url, new HttpEntity<>(body, jsonHeaders()), Map.class);
            Map<String, Object> responseBody = response.getBody();
            if (responseBody == null) return List.of();

            List<List<Object>> documents = (List<List<Object>>) responseBody.get("documents");
            List<List<Object>> metadatas = (List<List<Object>>) responseBody.get("metadatas");
            List<List<Object>> ids = (List<List<Object>>) responseBody.get("ids");

            List<Map<String, Object>> results = new ArrayList<>();
            if (documents != null && !documents.isEmpty()) {
                for (int i = 0; i < documents.get(0).size(); i++) {
                    Map<String, Object> item = new HashMap<>();
                    item.put("document", documents.get(0).get(i));
                    if (metadatas != null && !metadatas.isEmpty()) {
                        item.put("metadata", metadatas.get(0).get(i));
                    }
                    if (ids != null && !ids.isEmpty()) {
                        item.put("id", ids.get(0).get(i));
                    }
                    results.add(item);
                }
            }
            return results;
        } catch (Exception e) {
            throw new BusinessException(ResultCode.CHROMA_ERROR, "Chroma 检索失败: " + e.getMessage());
        }
    }

    public void ensureCollectionExists() {
        String checkUrl = chromaConfig.getUrl() + "/api/v1/collections/" + chromaConfig.getCollectionName();
        try {
            restTemplate.getForEntity(checkUrl, Map.class);
        } catch (Exception e) {
            String createUrl = chromaConfig.getUrl() + "/api/v1/collections";
            Map<String, Object> body = new HashMap<>();
            body.put("name", chromaConfig.getCollectionName());
            try {
                restTemplate.postForEntity(createUrl, new HttpEntity<>(body, jsonHeaders()), Map.class);
            } catch (Exception ex) {
                throw new BusinessException(ResultCode.CHROMA_ERROR, "Chroma 集合创建失败: " + ex.getMessage());
            }
        }
    }

    public long count() {
        String url = chromaConfig.getUrl() + "/api/v1/collections/" + chromaConfig.getCollectionName() + "/count";
        try {
            var response = restTemplate.getForEntity(url, Long.class);
            return response.getBody() != null ? response.getBody() : 0;
        } catch (Exception e) {
            return 0;
        }
    }

    public List<Map<String, Object>> listKnowledge() {
        String url = chromaConfig.getUrl() + "/api/v1/collections/" + chromaConfig.getCollectionName() + "/get";
        try {
            var response = restTemplate.postForEntity(url, new HttpEntity<>(null, jsonHeaders()), Map.class);
            Map<String, Object> body = response.getBody();
            if (body == null) return List.of();

            List<Object> ids = (List<Object>) body.get("ids");
            List<Object> documents = (List<Object>) body.get("documents");
            List<Object> metadatas = (List<Object>) body.get("metadatas");

            List<Map<String, Object>> results = new ArrayList<>();
            if (ids != null) {
                for (int i = 0; i < ids.size(); i++) {
                    Map<String, Object> item = new HashMap<>();
                    item.put("id", ids.get(i));
                    if (documents != null && i < documents.size()) item.put("document", documents.get(i));
                    if (metadatas != null && i < metadatas.size()) item.put("metadata", metadatas.get(i));
                    results.add(item);
                }
            }
            return results;
        } catch (Exception e) {
            throw new BusinessException(ResultCode.CHROMA_ERROR, "Chroma 查询失败: " + e.getMessage());
        }
    }

    private HttpHeaders jsonHeaders() {
        HttpHeaders headers = new HttpHeaders();
        headers.setContentType(MediaType.APPLICATION_JSON);
        return headers;
    }
}
