// @generated by AI
package com.smarthealth.service;

import com.smarthealth.common.BusinessException;
import com.smarthealth.common.ResultCode;
import com.smarthealth.dto.request.AiConfigRequest;
import com.smarthealth.dto.response.AiConfigResponse;
import com.smarthealth.entity.UserAiConfig;
import com.smarthealth.mapper.UserAiConfigMapper;
import com.smarthealth.util.EncryptionUtil;
import lombok.RequiredArgsConstructor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.client.RestTemplate;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

@Service
@RequiredArgsConstructor
public class UserAiConfigService {

    private static final Logger log = LoggerFactory.getLogger(UserAiConfigService.class);

    private final UserAiConfigMapper configMapper;
    private final RestTemplate restTemplate;
    private final EncryptionUtil encryptionUtil;

    public AiConfigResponse getConfig(Long userId) {
        UserAiConfig config = configMapper.findByUserId(userId);
        if (config == null) {
            return new AiConfigResponse("DEFAULT", null, null, null, null);
        }
        return toResponse(config);
    }

    @Transactional(rollbackFor = Exception.class)
    public AiConfigResponse saveConfig(Long userId, String role, AiConfigRequest request) {
        String provider = request.getProvider() != null ? request.getProvider() : "DEFAULT";

        if ("LOCAL".equals(provider) && !"VIP".equals(role)) {
            throw new BusinessException(ResultCode.FORBIDDEN, "非 VIP 用户不能使用本地模型");
        }

        String customProvider = null;
        if ("CUSTOM".equals(provider)) {
            if (request.getApiKey() == null || request.getApiKey().isBlank()) {
                throw new BusinessException(ResultCode.BAD_REQUEST, "自定义模式需提供 API Key");
            }
            customProvider = request.getCustomProvider() != null ? request.getCustomProvider() : "deepseek";
            testConnection(request, customProvider);
        }

        String apiKey = "CUSTOM".equals(provider) ? encryptionUtil.encrypt(request.getApiKey()) : null;
        String apiUrl = "CUSTOM".equals(provider) ? request.getApiUrl() : null;
        String model = "CUSTOM".equals(provider) ? request.getModel() : null;

        UserAiConfig existing = configMapper.findByUserId(userId);
        if (existing == null) {
            UserAiConfig config = new UserAiConfig();
            config.setUserId(userId);
            config.setProvider(provider);
            config.setCustomProvider(customProvider);
            config.setApiKey(apiKey);
            config.setApiUrl(apiUrl);
            config.setModel(model);
            config.setCreatedAt(LocalDateTime.now());
            config.setUpdatedAt(LocalDateTime.now());
            configMapper.insert(config);
            return toResponse(config);
        } else {
            existing.setProvider(provider);
            existing.setCustomProvider(customProvider);
            existing.setApiKey(apiKey);
            existing.setApiUrl(apiUrl);
            existing.setModel(model);
            existing.setUpdatedAt(LocalDateTime.now());
            configMapper.update(existing);
            return toResponse(existing);
        }
    }

    @Transactional(rollbackFor = Exception.class)
    public void deleteConfig(Long userId) {
        configMapper.deleteByUserId(userId);
    }

    void testConnection(AiConfigRequest request, String customProvider) {
        try {
            String defaultUrl = switch (customProvider) {
                case "openai" -> "https://api.openai.com/v1/chat/completions";
                case "claude" -> "https://api.anthropic.com/v1/messages";
                default -> "https://api.deepseek.com/v1/chat/completions";
            };
            String url = request.getApiUrl() != null ? request.getApiUrl() : defaultUrl;

            // SSRF protection: validate URL
            java.net.URL parsedUrl = new java.net.URL(url);
            String protocol = parsedUrl.getProtocol().toLowerCase();
            String host = parsedUrl.getHost().toLowerCase();

            if (!"https".equals(protocol)) {
                throw new BusinessException(ResultCode.BAD_REQUEST, "API 地址必须使用 HTTPS");
            }

            if (isInternalHost(host)) {
                throw new BusinessException(ResultCode.BAD_REQUEST, "不允许访问内网地址");
            }

            HttpHeaders headers = new HttpHeaders();
            headers.setContentType(MediaType.APPLICATION_JSON);

            if ("claude".equals(customProvider)) {
                headers.set("x-api-key", request.getApiKey());
                headers.set("anthropic-version", "2023-06-01");

                String model = request.getModel() != null ? request.getModel() : "claude-3-haiku-20240307";
                Map<String, Object> requestBody = Map.of(
                        "model", model,
                        "max_tokens", 5,
                        "messages", List.of(
                                Map.of("role", "user", "content", "test")
                        )
                );
                HttpEntity<Map<String, Object>> httpEntity = new HttpEntity<>(requestBody, headers);
                ResponseEntity<Map> response = restTemplate.postForEntity(url, httpEntity, Map.class);
                if (response.getStatusCode().isError()) {
                    throw new BusinessException(ResultCode.BAD_REQUEST, "API Key 验证失败");
                }
            } else {
                headers.setBearerAuth(request.getApiKey());
                String model = request.getModel() != null ? request.getModel() : "deepseek-chat";
                Map<String, Object> requestBody = Map.of(
                        "model", model,
                        "messages", List.of(
                                Map.of("role", "user", "content", "test")
                        ),
                        "max_tokens", 5
                );
                HttpEntity<Map<String, Object>> httpEntity = new HttpEntity<>(requestBody, headers);
                ResponseEntity<Map> response = restTemplate.postForEntity(url, httpEntity, Map.class);
                if (response.getStatusCode().isError()) {
                    throw new BusinessException(ResultCode.BAD_REQUEST, "API Key 验证失败");
                }
            }

            log.info("AI connection test succeeded for url: {}", url);
        } catch (BusinessException e) {
            throw e;
        } catch (Exception e) {
            log.warn("AI connection test failed for url: {}", e.getMessage());
            throw new BusinessException(ResultCode.BAD_REQUEST, "API 连接测试失败");
        }
    }

    private boolean isInternalHost(String host) {
        if (host.equals("localhost") || host.equals("127.0.0.1") || host.equals("0.0.0.0")
                || host.equals("::1") || host.equals("[::1]")
                || host.endsWith(".local") || host.endsWith(".internal")) {
            return true;
        }
        if (host.matches("^(10|127|169\\.254|172\\.(1[6-9]|2[0-9]|3[01])|192\\.168)\\..+")) {
            return true;
        }
        return false;
    }

    private AiConfigResponse toResponse(UserAiConfig config) {
        String decryptedKey = config.getApiKey() != null ? encryptionUtil.decrypt(config.getApiKey()) : null;
        String maskedKey = decryptedKey != null ? maskApiKey(decryptedKey) : null;
        return new AiConfigResponse(config.getProvider(), config.getCustomProvider(), maskedKey, config.getApiUrl(), config.getModel());
    }

    public static String maskApiKey(String key) {
        if (key == null || key.length() < 8) {
            return "****";
        }
        int keep = Math.min(6, key.length() - 4);
        if (keep < 2) {
            keep = 2;
        }
        return key.substring(0, keep) + "****" + key.substring(key.length() - 4);
    }
}
