// @generated by AI
package com.smarthealth.service;

import com.smarthealth.common.BusinessException;
import com.smarthealth.common.ResultCode;
import com.smarthealth.dto.request.AiConfigRequest;
import com.smarthealth.dto.response.AiConfigResponse;
import com.smarthealth.entity.UserAiConfig;
import com.smarthealth.mapper.UserAiConfigMapper;
import lombok.RequiredArgsConstructor;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.http.HttpEntity;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.client.RestTemplate;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

@Service
@RequiredArgsConstructor
public class UserAiConfigService {

    private static final Logger log = LoggerFactory.getLogger(UserAiConfigService.class);

    private final UserAiConfigMapper configMapper;
    private final RestTemplate restTemplate;

    public AiConfigResponse getConfig(Long userId) {
        UserAiConfig config = configMapper.findByUserId(userId);
        if (config == null) {
            return new AiConfigResponse("DEFAULT", null, null, null);
        }
        return toResponse(config);
    }

    @Transactional(rollbackFor = Exception.class)
    public AiConfigResponse saveConfig(Long userId, AiConfigRequest request) {
        String provider = request.getProvider() != null ? request.getProvider() : "DEFAULT";

        if ("CUSTOM".equals(provider)) {
            if (request.getApiKey() == null || request.getApiKey().isBlank()) {
                throw new BusinessException(ResultCode.BAD_REQUEST, "自定义模式需提供 API Key");
            }
            testConnection(request);
        }

        String customProvider = "CUSTOM".equals(provider)
                ? (request.getCustomProvider() != null ? request.getCustomProvider() : "deepseek")
                : "deepseek";
        String apiKey = "CUSTOM".equals(provider) ? request.getApiKey() : null;
        String apiUrl = "CUSTOM".equals(provider) ? request.getApiUrl() : null;
        String model = "CUSTOM".equals(provider) ? request.getModel() : null;

        UserAiConfig existing = configMapper.findByUserId(userId);
        if (existing == null) {
            UserAiConfig config = new UserAiConfig();
            config.setUserId(userId);
            config.setProvider(provider);
            config.setCustomProvider(customProvider);
            config.setApiKey(apiKey);
            config.setApiUrl(apiUrl);
            config.setModel(model);
            config.setCreatedAt(LocalDateTime.now());
            config.setUpdatedAt(LocalDateTime.now());
            configMapper.insert(config);
            return toResponse(config);
        } else {
            existing.setProvider(provider);
            existing.setCustomProvider(customProvider);
            existing.setApiKey(apiKey);
            existing.setApiUrl(apiUrl);
            existing.setModel(model);
            existing.setUpdatedAt(LocalDateTime.now());
            configMapper.update(existing);
            return toResponse(existing);
        }
    }

    @Transactional(rollbackFor = Exception.class)
    public void deleteConfig(Long userId) {
        configMapper.deleteByUserId(userId);
    }

    void testConnection(AiConfigRequest request) {
        try {
            HttpHeaders headers = new HttpHeaders();
            headers.setContentType(MediaType.APPLICATION_JSON);
            headers.setBearerAuth(request.getApiKey());

            String url = request.getApiUrl() != null ? request.getApiUrl()
                    : "https://api.deepseek.com/v1/chat/completions";
            String model = request.getModel() != null ? request.getModel() : "deepseek-chat";

            Map<String, Object> requestBody = Map.of(
                    "model", model,
                    "messages", List.of(
                            Map.of("role", "user", "content", "test")
                    ),
                    "max_tokens", 5
            );

            HttpEntity<Map<String, Object>> httpEntity = new HttpEntity<>(requestBody, headers);
            ResponseEntity<Map> response = restTemplate.postForEntity(url, httpEntity, Map.class);
            if (response.getStatusCode().isError()) {
                throw new BusinessException(ResultCode.BAD_REQUEST, "API Key 验证失败: " + response.getStatusCode());
            }
            log.info("AI connection test succeeded for url: {}", url);
        } catch (BusinessException e) {
            throw e;
        } catch (Exception e) {
            throw new BusinessException(ResultCode.BAD_REQUEST, "API 连接测试失败: " + e.getMessage());
        }
    }

    private AiConfigResponse toResponse(UserAiConfig config) {
        String maskedKey = config.getApiKey() != null ? maskApiKey(config.getApiKey()) : null;
        return new AiConfigResponse(config.getProvider(), maskedKey, config.getApiUrl(), config.getModel());
    }

    public static String maskApiKey(String key) {
        if (key == null || key.length() < 8) {
            return "****";
        }
        return key.substring(0, Math.min(6, key.length() - 4)) + "****" + key.substring(key.length() - 4);
    }
}
