// @generated by AI
package com.smarthealth.service;

import com.smarthealth.common.BusinessException;
import com.smarthealth.common.ResultCode;
import com.smarthealth.dto.request.AddWeightRequest;
import com.smarthealth.dto.response.WeightRecordResponse;
import com.smarthealth.dto.response.WeightTrendResponse;
import com.smarthealth.entity.WeightRecord;
import com.smarthealth.mapper.WeightRecordMapper;
import lombok.RequiredArgsConstructor;
import org.springframework.stereotype.Service;
import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

@Service
@RequiredArgsConstructor
public class WeightService {

    private final WeightRecordMapper weightRecordMapper;

    public void addWeight(Long userId, AddWeightRequest request) {
        WeightRecord record = new WeightRecord();
        record.setUserId(userId);
        record.setWeight(request.getWeight());
        record.setRecordDate(request.getRecordDate());
        weightRecordMapper.insert(record);
    }

    public List<WeightRecordResponse> getHistory(Long userId) {
        return weightRecordMapper.findByUserId(userId).stream()
                .map(r -> new WeightRecordResponse(r.getId(), r.getWeight(), r.getRecordDate()))
                .collect(Collectors.toList());
    }

    public WeightTrendResponse getTrend(Long userId, String period) {
        List<WeightRecord> allRecords = weightRecordMapper.findByUserId(userId);
        if (allRecords == null || allRecords.isEmpty()) {
            return new WeightTrendResponse(List.of(), List.of());
        }

        LocalDate startDate;
        LocalDate now = LocalDate.now();
        switch (period) {
            case "week":
                startDate = now.minusDays(7);
                break;
            case "month":
                startDate = now.minusMonths(1);
                break;
            case "year":
                startDate = now.minusYears(1);
                break;
            default:
                startDate = now.minusDays(7);
        }

        DateTimeFormatter fmt = DateTimeFormatter.ofPattern("MM-dd");
        List<String> dates = new ArrayList<>();
        List<BigDecimal> values = new ArrayList<>();

        for (WeightRecord record : allRecords) {
            if (!record.getRecordDate().isBefore(startDate)) {
                dates.add(record.getRecordDate().format(fmt));
                values.add(record.getWeight());
            }
        }

        return new WeightTrendResponse(dates, values);
    }

    public void deleteWeight(Long userId, Long recordId) {
        WeightRecord record = weightRecordMapper.findById(recordId);
        if (record == null) {
            throw new BusinessException(ResultCode.NOT_FOUND, "体重记录不存在");
        }
        if (!record.getUserId().equals(userId)) {
            throw new BusinessException(ResultCode.FORBIDDEN, "无权限删除该记录");
        }
        weightRecordMapper.deleteById(recordId);
    }

    public String analyzeTrend(Long userId) {
        List<WeightRecord> records = weightRecordMapper.findByUserId(userId);
        if (records == null || records.size() < 2) {
            return "暂无足够的体重记录分析趋势";
        }

        int n = records.size();
        WeightRecord first = records.get(0);
        WeightRecord last = records.get(n - 1);

        int comparison = last.getWeight().compareTo(first.getWeight());
        if (comparison < 0) {
            return "体重持续下降，保持当前计划强度。";
        } else if (comparison > 0) {
            return "体重上升，建议减少高热量饮食，增加运动频率。";
        } else {
            return "体重无明显变化，建议调整饮食结构，提高运动强度。";
        }
    }
}
