// @generated by AI
package com.smarthealth.dto.request;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotNull;
import lombok.Data;
import java.math.BigDecimal;
import java.time.LocalDate;

@Data
@Schema(description = "添加体重记录请求")
public class AddWeightRequest {

    @NotNull(message = "体重不能为空")
    @Schema(description = "体重(kg)", example = "79.5")
    private BigDecimal weight;

    @NotNull(message = "记录日期不能为空")
    @Schema(description = "记录日期", example = "2026-06-08")
    private LocalDate recordDate;
}
