// @generated by AI
package com.smarthealth.dto.request;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.Pattern;
import jakarta.validation.constraints.Size;
import lombok.Data;

@Data
@Schema(description = "AI 配置请求")
public class AiConfigRequest {

    @Pattern(regexp = "^(DEFAULT|CUSTOM|LOCAL)$", message = "provider 必须为 DEFAULT / CUSTOM / LOCAL")
    @Schema(description = "AI 提供方: DEFAULT / CUSTOM / LOCAL", example = "CUSTOM")
    private String provider;

    @Pattern(regexp = "^(deepseek|openai|claude)$", message = "customProvider 必须为 deepseek / openai / claude")
    @Schema(description = "自定义 AI 厂商（provider=CUSTOM 时生效）", example = "deepseek")
    private String customProvider;

    @Size(max = 500, message = "API Key 最多 500 字")
    @Schema(description = "自定义 API Key（provider=CUSTOM 时必填）", example = "sk-xxxxxxxx")
    private String apiKey;

    @Size(max = 500, message = "API 地址最多 500 字")
    @Pattern(regexp = "^(https?://).+", message = "API 地址必须以 http:// 或 https:// 开头")
    @Schema(description = "自定义 API 地址", example = "https://api.deepseek.com/v1/chat/completions")
    private String apiUrl;

    @Size(max = 100, message = "模型名最多 100 字")
    @Schema(description = "模型名称", example = "deepseek-chat")
    private String model;
}
