// @generated by AI
package com.smarthealth.dto.request;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.Size;
import lombok.Data;

@Data
@Schema(description = "智能问答请求")
public class ChatRequest {

    @NotBlank(message = "问题不能为空")
    @Size(max = 500, message = "问题最多500字")
    @Schema(description = "用户问题", example = "减脂期间晚餐怎么吃？")
    private String question;
}
