// @generated by AI
package com.smarthealth.dto.request;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import lombok.Data;
import java.util.Map;

@Data
@Schema(description = "新增健康知识请求")
public class CreateKnowledgeRequest {

    @NotBlank(message = "知识正文不能为空")
    @Schema(description = "健康知识正文", example = "减脂期间应控制总热量摄入，增加优质蛋白。")
    private String document;

    @Schema(description = "知识 metadata")
    private Metadata metadata;

    @Data
    @Schema(description = "知识元数据")
    public static class Metadata {

        @NotBlank(message = "分类不能为空")
        @Schema(description = "知识分类", example = "减脂饮食")
        private String category;

        @NotBlank(message = "标题不能为空")
        @Schema(description = "知识标题", example = "减脂期间饮食原则")
        private String title;

        @Schema(description = "关键词", example = "减脂,热量,蛋白质")
        private String keywords;

        @NotBlank(message = "状态不能为空")
        @Schema(description = "状态: enabled/disabled", example = "enabled")
        private String status;

        @NotBlank(message = "级别不能为空")
        @Schema(description = "级别: basic/vip/all", example = "all")
        private String level;
    }

    public Map<String, String> toMetadataMap() {
        Map<String, String> map = new java.util.HashMap<>();
        map.put("category", metadata.getCategory());
        map.put("title", metadata.getTitle());
        map.put("keywords", metadata.getKeywords() != null ? metadata.getKeywords() : "");
        map.put("status", metadata.getStatus());
        map.put("level", metadata.getLevel());
        return map;
    }
}
