// @generated by AI
package com.smarthealth.dto.request;

import io.swagger.v3.oas.annotations.media.Schema;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import lombok.Data;
import java.math.BigDecimal;

@Data
@Schema(description = "保存健康档案请求")
public class SaveProfileRequest {

    @NotNull(message = "年龄不能为空")
    @Schema(description = "年龄", example = "22")
    private Integer age;

    @NotBlank(message = "性别不能为空")
    @Schema(description = "性别", example = "男")
    private String gender;

    @NotNull(message = "身高不能为空")
    @Schema(description = "身高(cm)", example = "175.0")
    private BigDecimal height;

    @NotNull(message = "体重不能为空")
    @Schema(description = "体重(kg)", example = "80.0")
    private BigDecimal weight;

    @NotBlank(message = "活动水平不能为空")
    @Schema(description = "活动水平", example = "较低")
    private String activityLevel;

    @Schema(description = "饮食偏好", example = "少油少糖")
    private String dietPreference;

    @NotBlank(message = "健康目标不能为空")
    @Schema(description = "健康目标", example = "减脂")
    private String goal;
}
