// @generated by AI
package com.smarthealth.common;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.stereotype.Service;

import java.time.Duration;
import java.time.Instant;
import java.util.Map;
import java.util.concurrent.ConcurrentHashMap;

@Service
public class RateLimitService {

    private static final Logger log = LoggerFactory.getLogger(RateLimitService.class);

    private final Map<String, RateLimitEntry> store = new ConcurrentHashMap<>();

    public boolean isAllowed(String key, int maxRequests, Duration window) {
        RateLimitEntry entry = store.compute(key, (k, existing) -> {
            Instant now = Instant.now();
            if (existing == null || now.isAfter(existing.getWindowEnd())) {
                return new RateLimitEntry(now.plus(window), 1);
            }
            existing.incrementCount();
            return existing;
        });
        boolean allowed = entry.getCount() <= maxRequests;
        if (!allowed) {
            log.warn("Rate limit exceeded for key: {} (count: {}, max: {})", key, entry.getCount(), maxRequests);
        }
        return allowed;
    }

    private static class RateLimitEntry {
        private final Instant windowEnd;
        private int count;

        RateLimitEntry(Instant windowEnd, int count) {
            this.windowEnd = windowEnd;
            this.count = count;
        }

        Instant getWindowEnd() { return windowEnd; }
        int getCount() { return count; }
        void incrementCount() { count++; }
    }
}
