// @generated by AI
package com.smarthealth.service;

import com.smarthealth.common.BusinessException;
import com.smarthealth.dto.request.ChatRequest;
import com.smarthealth.dto.response.ChatResponse;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.util.List;
import java.util.Map;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class ChatServiceTest {

    @Mock
    private RagService ragService;

    @Mock
    private DeepSeekService deepSeekService;

    @InjectMocks
    private ChatService chatService;

    private ChatRequest request;

    @BeforeEach
    void setUp() {
        request = new ChatRequest();
        request.setQuestion("减脂期间晚餐怎么吃？");
    }

    @Test
    void askQuestion_shouldReturnAnswer_whenVIP() {
        Map<String, Object> ragItem = Map.of(
                "document", "减脂晚餐建议控制热量",
                "metadata", Map.of("title", "减脂指南", "category", "饮食")
        );
        when(ragService.query(anyString(), anyInt(), eq("VIP"))).thenReturn(List.of(ragItem));
        when(deepSeekService.chat(anyString(), anyString())).thenReturn("减脂期间晚餐建议控制总热量摄入");

        ChatResponse response = chatService.askQuestion("VIP", request);

        assertNotNull(response);
        assertTrue(response.getAnswer().contains("减脂"));
        assertEquals(1, response.getReferences().size());
        assertEquals("减脂指南", response.getReferences().get(0).getTitle());
    }

    @Test
    void askQuestion_shouldThrow_whenUSER() {
        BusinessException ex = assertThrows(BusinessException.class,
                () -> chatService.askQuestion("USER", request));
        assertEquals(403, ex.getCode());
    }

    @Test
    void askQuestion_shouldWork_withoutRagResults() {
        when(ragService.query(anyString(), anyInt(), eq("VIP"))).thenReturn(List.of());
        when(deepSeekService.chat(anyString(), anyString())).thenReturn("合理饮食建议");

        ChatResponse response = chatService.askQuestion("VIP", request);

        assertNotNull(response);
        assertTrue(response.getAnswer().contains("合理饮食"));
        assertTrue(response.getReferences().isEmpty());
    }
}
