// @generated by AI
package com.smarthealth.service;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class ChromaInitServiceTest {

    @Mock
    private RagService ragService;

    @InjectMocks
    private ChromaInitService chromaInitService;

    @Test
    void init_shouldSeed_whenCollectionEmpty() {
        when(ragService.count()).thenReturn(0L);

        chromaInitService.init();

        verify(ragService).ensureCollectionExists();
        verify(ragService, atLeastOnce()).addKnowledge(anyString(), anyMap());
    }

    @Test
    void init_shouldSkipSeed_whenCollectionNotEmpty() {
        when(ragService.count()).thenReturn(5L);

        chromaInitService.init();

        verify(ragService).ensureCollectionExists();
        verify(ragService, never()).addKnowledge(anyString(), anyMap());
    }

    @Test
    void init_shouldNotThrow_whenChromaUnavailable() {
        doThrow(new RuntimeException("Chroma not reachable")).when(ragService).ensureCollectionExists();

        chromaInitService.init();

        verify(ragService).ensureCollectionExists();
        verify(ragService, never()).count();
        verify(ragService, never()).addKnowledge(anyString(), anyMap());
    }
}
