// @generated by AI
package com.smarthealth.service;

import com.smarthealth.config.ChromaConfig;
import com.smarthealth.dto.response.HealthResponse;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.web.client.RestTemplate;

import javax.sql.DataSource;
import java.sql.Connection;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class HealthServiceTest {

    @Mock
    private DataSource dataSource;

    @Mock
    private ChromaConfig chromaConfig;

    @Mock
    private RestTemplate restTemplate;

    @InjectMocks
    private HealthService healthService;

    @Test
    void check_shouldReturnAllUP() throws Exception {
        Connection conn = mock(Connection.class);
        when(dataSource.getConnection()).thenReturn(conn);
        when(conn.isValid(2)).thenReturn(true);
        when(chromaConfig.getUrl()).thenReturn("http://localhost:8000");
        when(restTemplate.getForEntity("http://localhost:8000/api/v1/heartbeat", String.class))
                .thenReturn(null);

        HealthResponse response = healthService.check();

        assertEquals("UP", response.getMysql());
        assertEquals("UP", response.getChroma());
    }

    @Test
    void check_shouldReturnDOWN_whenMysqlFails() throws Exception {
        when(dataSource.getConnection()).thenThrow(new RuntimeException("Connection refused"));
        when(chromaConfig.getUrl()).thenReturn("http://localhost:8000");
        when(restTemplate.getForEntity("http://localhost:8000/api/v1/heartbeat", String.class))
                .thenReturn(null);

        HealthResponse response = healthService.check();

        assertEquals("DOWN", response.getMysql());
        assertEquals("UP", response.getChroma());
    }

    @Test
    void check_shouldReturnDOWN_whenChromaFails() throws Exception {
        Connection conn = mock(Connection.class);
        when(dataSource.getConnection()).thenReturn(conn);
        when(conn.isValid(2)).thenReturn(true);
        when(chromaConfig.getUrl()).thenReturn("http://localhost:8000");
        when(restTemplate.getForEntity("http://localhost:8000/api/v1/heartbeat", String.class))
                .thenThrow(new RuntimeException("Connection refused"));

        HealthResponse response = healthService.check();

        assertEquals("UP", response.getMysql());
        assertEquals("DOWN", response.getChroma());
    }
}
