// @generated by AI
package com.smarthealth.service;

import com.smarthealth.common.BusinessException;
import com.smarthealth.dto.response.GenerateCountResponse;
import com.smarthealth.dto.response.PlanHistoryResponse;
import com.smarthealth.entity.*;
import com.smarthealth.mapper.*;
import com.fasterxml.jackson.databind.ObjectMapper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class PlanServiceTest {

    @Mock
    private PlanMapper planMapper;

    @Mock
    private PlanGenerateRecordMapper generateRecordMapper;

    @Mock
    private ProfileMapper profileMapper;

    @Mock
    private WeightService weightService;

    @Mock
    private DeepSeekService deepSeekService;

    @Mock
    private RagService ragService;

    @Mock
    private ObjectMapper objectMapper;

    @InjectMocks
    private PlanService planService;

    private HealthProfile profile;
    private Plan plan;

    @BeforeEach
    void setUp() {
        profile = new HealthProfile();
        profile.setId(1L);
        profile.setUserId(1L);
        profile.setAge(22);
        profile.setGender("男");
        profile.setHeight(BigDecimal.valueOf(175));
        profile.setWeight(BigDecimal.valueOf(80));
        profile.setActivityLevel("较低");
        profile.setDietPreference("少油少糖");
        profile.setGoal("减脂");

        plan = new Plan();
        plan.setId(1L);
        plan.setUserId(1L);
        plan.setPlanType("COMBINED");
        plan.setPlanLevel("BASIC");
        plan.setPlanContent("{}");
        plan.setTrendSummary("体重无明显变化");
        plan.setCreateTime(LocalDateTime.now());
    }

    @Test
    void getHistory_shouldReturnPlanList() {
        when(planMapper.findByUserId(1L)).thenReturn(List.of(plan));

        List<PlanHistoryResponse> history = planService.getHistory(1L);

        assertEquals(1, history.size());
    }

    @Test
    void getDetail_shouldReturn_whenOwnPlan() {
        when(planMapper.findById(1L)).thenReturn(plan);

        var detail = planService.getDetail(1L, "USER", 1L);

        assertNotNull(detail);
    }

    @Test
    void getDetail_shouldThrow_whenNotOwnPlan() {
        when(planMapper.findById(1L)).thenReturn(plan);

        assertThrows(BusinessException.class, () -> planService.getDetail(2L, "USER", 1L));
    }

    @Test
    void getGenerateCount_shouldReturnCorrectLimit_forUser() {
        when(generateRecordMapper.findByUserIdAndDate(eq(1L), any(LocalDate.class)))
                .thenReturn(null);

        GenerateCountResponse count = planService.getGenerateCount(1L, "USER");

        assertEquals(0, count.getUsedCount());
        assertEquals(2, count.getLimitCount());
        assertEquals(2, count.getRemainingCount());
    }

    @Test
    void getGenerateCount_shouldReturnCorrectLimit_forVIP() {
        PlanGenerateRecord record = new PlanGenerateRecord();
        record.setGenerateCount(3);
        when(generateRecordMapper.findByUserIdAndDate(eq(1L), any(LocalDate.class)))
                .thenReturn(record);

        GenerateCountResponse count = planService.getGenerateCount(1L, "VIP");

        assertEquals(3, count.getUsedCount());
        assertEquals(5, count.getLimitCount());
        assertEquals(2, count.getRemainingCount());
    }
}
