// @generated by AI
package com.smarthealth.service;

import com.smarthealth.common.BusinessException;
import com.smarthealth.dto.request.SaveProfileRequest;
import com.smarthealth.dto.response.ProfileResponse;
import com.smarthealth.entity.HealthProfile;
import com.smarthealth.mapper.ProfileMapper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.ArgumentCaptor;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.math.BigDecimal;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class ProfileServiceTest {

    @Mock
    private ProfileMapper profileMapper;

    @InjectMocks
    private ProfileService profileService;

    private HealthProfile existingProfile;
    private SaveProfileRequest saveRequest;

    @BeforeEach
    void setUp() {
        existingProfile = new HealthProfile();
        existingProfile.setId(1L);
        existingProfile.setUserId(1L);
        existingProfile.setAge(22);
        existingProfile.setGender("男");
        existingProfile.setHeight(BigDecimal.valueOf(175));
        existingProfile.setWeight(BigDecimal.valueOf(80));
        existingProfile.setActivityLevel("较低");
        existingProfile.setDietPreference("少油少糖");
        existingProfile.setGoal("减脂");

        saveRequest = new SaveProfileRequest();
        saveRequest.setAge(22);
        saveRequest.setGender("男");
        saveRequest.setHeight(BigDecimal.valueOf(175));
        saveRequest.setWeight(BigDecimal.valueOf(80));
        saveRequest.setActivityLevel("较低");
        saveRequest.setDietPreference("少油少糖");
        saveRequest.setGoal("减脂");
    }

    @Test
    void getProfile_shouldReturn_whenExists() {
        when(profileMapper.findByUserId(1L)).thenReturn(existingProfile);

        ProfileResponse response = profileService.getProfile(1L);

        assertNotNull(response);
        assertEquals(22, response.getAge());
        assertEquals("男", response.getGender());
        assertEquals(BigDecimal.valueOf(175), response.getHeight());
        assertEquals(BigDecimal.valueOf(80), response.getWeight());
        assertEquals("较低", response.getActivityLevel());
        assertEquals("少油少糖", response.getDietPreference());
        assertEquals("减脂", response.getGoal());
    }

    @Test
    void getProfile_shouldThrow_whenNotFound() {
        when(profileMapper.findByUserId(1L)).thenReturn(null);

        BusinessException ex = assertThrows(BusinessException.class,
                () -> profileService.getProfile(1L));
        assertEquals(404, ex.getCode());
    }

    @Test
    void saveProfile_shouldInsert_whenNoExisting() {
        when(profileMapper.findByUserId(1L)).thenReturn(null);

        profileService.saveProfile(1L, saveRequest);

        ArgumentCaptor<HealthProfile> captor = ArgumentCaptor.forClass(HealthProfile.class);
        verify(profileMapper).insert(captor.capture());
        assertEquals(1L, captor.getValue().getUserId());
        assertEquals(22, captor.getValue().getAge());
    }

    @Test
    void saveProfile_shouldThrow_whenAlreadyExists() {
        when(profileMapper.findByUserId(1L)).thenReturn(existingProfile);

        BusinessException ex = assertThrows(BusinessException.class,
                () -> profileService.saveProfile(1L, saveRequest));
        assertEquals(409, ex.getCode());
    }

    @Test
    void updateProfile_shouldUpdate_whenExists() {
        when(profileMapper.findByUserId(1L)).thenReturn(existingProfile);

        profileService.updateProfile(1L, saveRequest);

        ArgumentCaptor<HealthProfile> captor = ArgumentCaptor.forClass(HealthProfile.class);
        verify(profileMapper).update(captor.capture());
        assertEquals(1L, captor.getValue().getId());
        assertEquals(22, captor.getValue().getAge());
    }

    @Test
    void updateProfile_shouldThrow_whenNotFound() {
        when(profileMapper.findByUserId(1L)).thenReturn(null);

        BusinessException ex = assertThrows(BusinessException.class,
                () -> profileService.updateProfile(1L, saveRequest));
        assertEquals(404, ex.getCode());
    }
}
