// @generated by AI
package com.smarthealth.service;

import com.smarthealth.common.BusinessException;
import com.smarthealth.dto.request.LoginRequest;
import com.smarthealth.dto.request.RegisterRequest;
import com.smarthealth.dto.response.LoginResponse;
import com.smarthealth.dto.response.UserResponse;
import com.smarthealth.entity.User;
import com.smarthealth.mapper.UserMapper;
import com.smarthealth.security.JwtTokenProvider;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.security.crypto.password.PasswordEncoder;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class UserServiceTest {

    @Mock
    private UserMapper userMapper;

    @Mock
    private PasswordEncoder passwordEncoder;

    @Mock
    private JwtTokenProvider jwtTokenProvider;

    @InjectMocks
    private UserService userService;

    private User testUser;
    private RegisterRequest registerRequest;
    private LoginRequest loginRequest;

    @BeforeEach
    void setUp() {
        testUser = new User();
        testUser.setId(1L);
        testUser.setUsername("testuser");
        testUser.setPassword("encodedPassword");
        testUser.setRole("USER");
        testUser.setStatus(1);

        registerRequest = new RegisterRequest();
        registerRequest.setUsername("newuser");
        registerRequest.setPassword("123456");

        loginRequest = new LoginRequest();
        loginRequest.setUsername("testuser");
        loginRequest.setPassword("123456");
    }

    @Test
    void register_shouldSucceed_whenUsernameNotExists() {
        when(userMapper.findByUsername("newuser")).thenReturn(null);
        when(passwordEncoder.encode("123456")).thenReturn("encodedPassword");

        userService.register(registerRequest);

        verify(userMapper).insert(any(User.class));
    }

    @Test
    void register_shouldThrow_whenUsernameExists() {
        when(userMapper.findByUsername("testuser")).thenReturn(testUser);

        BusinessException ex = assertThrows(BusinessException.class,
                () -> userService.register(new RegisterRequest() {{
                    setUsername("testuser");
                    setPassword("123456");
                }}));
        assertEquals(409, ex.getCode());
    }

    @Test
    void login_shouldReturnToken_whenCredentialsValid() {
        when(userMapper.findByUsername("testuser")).thenReturn(testUser);
        when(passwordEncoder.matches("123456", "encodedPassword")).thenReturn(true);
        when(jwtTokenProvider.generateToken(1L, "testuser", "USER")).thenReturn("jwt_token");

        LoginResponse response = userService.login(loginRequest);

        assertNotNull(response);
        assertEquals("testuser", response.getUsername());
        assertEquals("USER", response.getRole());
        assertEquals("jwt_token", response.getToken());
    }

    @Test
    void login_shouldThrow_whenPasswordWrong() {
        when(userMapper.findByUsername("testuser")).thenReturn(testUser);
        when(passwordEncoder.matches("123456", "encodedPassword")).thenReturn(false);

        assertThrows(BusinessException.class, () -> userService.login(loginRequest));
    }

    @Test
    void login_shouldThrow_whenUserDisabled() {
        testUser.setStatus(0);
        when(userMapper.findByUsername("testuser")).thenReturn(testUser);

        assertThrows(BusinessException.class, () -> userService.login(loginRequest));
    }

    @Test
    void getCurrentUser_shouldReturnUserResponse() {
        when(userMapper.findById(1L)).thenReturn(testUser);

        UserResponse response = userService.getCurrentUser(1L);

        assertEquals("testuser", response.getUsername());
        assertEquals("USER", response.getRole());
        assertEquals(1, response.getStatus());
    }
}
