// @generated by AI
package com.smarthealth.service;

import com.smarthealth.common.BusinessException;
import com.smarthealth.dto.request.AddWeightRequest;
import com.smarthealth.dto.response.WeightRecordResponse;
import com.smarthealth.dto.response.WeightTrendResponse;
import com.smarthealth.entity.WeightRecord;
import com.smarthealth.mapper.WeightRecordMapper;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

import static org.junit.jupiter.api.Assertions.*;
import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;

@ExtendWith(MockitoExtension.class)
class WeightServiceTest {

    @Mock
    private WeightRecordMapper weightRecordMapper;

    @InjectMocks
    private WeightService weightService;

    private WeightRecord record1;
    private WeightRecord record2;
    private AddWeightRequest addRequest;

    @BeforeEach
    void setUp() {
        record1 = new WeightRecord();
        record1.setId(1L);
        record1.setUserId(1L);
        record1.setWeight(BigDecimal.valueOf(80.0));
        record1.setRecordDate(LocalDate.of(2026, 6, 1));

        record2 = new WeightRecord();
        record2.setId(2L);
        record2.setUserId(1L);
        record2.setWeight(BigDecimal.valueOf(79.5));
        record2.setRecordDate(LocalDate.of(2026, 6, 8));

        addRequest = new AddWeightRequest();
        addRequest.setWeight(BigDecimal.valueOf(79.0));
        addRequest.setRecordDate(LocalDate.of(2026, 6, 9));
    }

    @Test
    void addWeight_shouldSucceed() {
        weightService.addWeight(1L, addRequest);
        verify(weightRecordMapper).insert(any(WeightRecord.class));
    }

    @Test
    void getHistory_shouldReturnRecords() {
        when(weightRecordMapper.findByUserId(1L)).thenReturn(List.of(record1, record2));

        List<WeightRecordResponse> history = weightService.getHistory(1L);

        assertEquals(2, history.size());
        assertEquals(BigDecimal.valueOf(80.0), history.get(0).getWeight());
        assertEquals(BigDecimal.valueOf(79.5), history.get(1).getWeight());
    }

    @Test
    void deleteWeight_shouldSucceed_whenOwnRecord() {
        when(weightRecordMapper.findById(1L)).thenReturn(record1);

        weightService.deleteWeight(1L, 1L);

        verify(weightRecordMapper).deleteById(1L);
    }

    @Test
    void deleteWeight_shouldThrow_whenNotOwnRecord() {
        when(weightRecordMapper.findById(1L)).thenReturn(record1);

        assertThrows(BusinessException.class, () -> weightService.deleteWeight(2L, 1L));
    }

    @Test
    void analyzeTrend_shouldReturnDescending_whenWeightDecreases() {
        when(weightRecordMapper.findByUserId(1L)).thenReturn(List.of(record1, record2));

        String trend = weightService.analyzeTrend(1L);

        assertTrue(trend.contains("下降"));
    }

    @Test
    void analyzeTrend_shouldReturnNoData_whenLessThanTwoRecords() {
        when(weightRecordMapper.findByUserId(1L)).thenReturn(List.of(record1));

        String trend = weightService.analyzeTrend(1L);

        assertTrue(trend.contains("暂无"));
    }

    @Test
    void getTrend_shouldReturnWeekData() {
        WeightRecord recent = new WeightRecord();
        recent.setWeight(BigDecimal.valueOf(78.0));
        recent.setRecordDate(LocalDate.now());
        when(weightRecordMapper.findByUserId(1L)).thenReturn(List.of(record1, record2, recent));

        WeightTrendResponse trend = weightService.getTrend(1L, "week");

        assertFalse(trend.getDates().isEmpty());
        assertEquals(trend.getDates().size(), trend.getValues().size());
    }

    @Test
    void getTrend_shouldReturnEmpty_whenNoRecords() {
        when(weightRecordMapper.findByUserId(1L)).thenReturn(List.of());

        WeightTrendResponse trend = weightService.getTrend(1L, "week");

        assertTrue(trend.getDates().isEmpty());
        assertTrue(trend.getValues().isEmpty());
    }

    @Test
    void getTrend_shouldSupportMonthPeriod() {
        when(weightRecordMapper.findByUserId(1L)).thenReturn(List.of(record1, record2));

        WeightTrendResponse trend = weightService.getTrend(1L, "month");

        assertTrue(trend.getDates().size() <= 2);
    }
}
