// @generated by AI
package com.smarthealth.entity;

import lombok.Data;
import java.time.LocalDateTime;

@Data
public class UserAiConfig {
    private Long id;
    private Long userId;
    private String provider;
    private String apiKey;
    private String apiUrl;
    private String model;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
}
