// @generated by AI
package com.smarthealth.controller;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.smarthealth.common.BusinessException;
import com.smarthealth.common.ResultCode;
import com.smarthealth.dto.request.ChatRequest;
import com.smarthealth.dto.response.ChatResponse;
import com.smarthealth.security.JwtAuthenticationFilter;
import com.smarthealth.security.JwtTokenProvider;
import com.smarthealth.security.UserPrincipal;
import com.smarthealth.service.ChatService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.http.MediaType;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.test.web.servlet.MockMvc;

import java.util.List;

import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@WebMvcTest(controllers = ChatController.class)
@AutoConfigureMockMvc(addFilters = false)
class ChatControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private ObjectMapper objectMapper;

    @MockBean
    private ChatService chatService;

    @MockBean
    private JwtTokenProvider jwtTokenProvider;

    @MockBean
    private JwtAuthenticationFilter jwtAuthenticationFilter;

    private void setAuth(String role) {
        String username = "VIP".equals(role) ? "vipuser" : "normaluser";
        UserPrincipal principal = new UserPrincipal(1L, username, role);
        SecurityContextHolder.getContext().setAuthentication(
                new UsernamePasswordAuthenticationToken(principal, null,
                        List.of(new SimpleGrantedAuthority("ROLE_" + role))));
    }

    @Test
    void askQuestion_shouldReturn200_whenVIP() throws Exception {
        setAuth("VIP");

        ChatRequest request = new ChatRequest();
        request.setQuestion("减脂期间晚餐怎么吃？");

        when(chatService.askQuestion("VIP", request))
                .thenReturn(new ChatResponse("减脂晚餐建议", List.of()));

        mockMvc.perform(post("/api/v1/chat/ask")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.code").value(200))
                .andExpect(jsonPath("$.data.answer").value("减脂晚餐建议"));
    }

    @Test
    void askQuestion_shouldReturn403_whenUSER() throws Exception {
        setAuth("USER");

        ChatRequest request = new ChatRequest();
        request.setQuestion("减脂期间晚餐怎么吃？");

        when(chatService.askQuestion("USER", request))
                .thenThrow(new BusinessException(ResultCode.FORBIDDEN, "无权限访问"));

        mockMvc.perform(post("/api/v1/chat/ask")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.code").value(403));
    }
}
