// @generated by AI
package com.smarthealth.controller;

import com.smarthealth.dto.response.GenerateCountResponse;
import com.smarthealth.dto.response.PlanDetailResponse;
import com.smarthealth.dto.response.PlanHistoryResponse;
import com.smarthealth.security.JwtAuthenticationFilter;
import com.smarthealth.security.JwtTokenProvider;
import com.smarthealth.security.UserPrincipal;
import com.smarthealth.service.PlanService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.test.web.servlet.MockMvc;

import java.time.LocalDateTime;
import java.util.List;
import java.util.Map;

import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@WebMvcTest(controllers = PlanController.class)
@AutoConfigureMockMvc(addFilters = false)
class PlanControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @MockBean
    private PlanService planService;

    @MockBean
    private JwtTokenProvider jwtTokenProvider;

    @MockBean
    private JwtAuthenticationFilter jwtAuthenticationFilter;

    private final PlanDetailResponse detailResponse = new PlanDetailResponse(
            1L, "COMBINED", "BASIC", Map.of("key", "value"),
            "体重持续下降", List.of(), LocalDateTime.now());

    @BeforeEach
    void setUp() {
        UserPrincipal principal = new UserPrincipal(1L, "testuser", "USER");
        SecurityContextHolder.getContext().setAuthentication(
                new UsernamePasswordAuthenticationToken(principal, null,
                        List.of(new SimpleGrantedAuthority("ROLE_USER"))));
    }

    @Test
    void generatePlan_shouldReturn200() throws Exception {
        when(planService.generatePlan(1L, "USER")).thenReturn(detailResponse);

        mockMvc.perform(post("/api/v1/plan/generate"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.code").value(200))
                .andExpect(jsonPath("$.data.planType").value("COMBINED"));
    }

    @Test
    void getHistory_shouldReturn200() throws Exception {
        when(planService.getHistory(1L))
                .thenReturn(List.of(
                        new PlanHistoryResponse(1L, "COMBINED", "BASIC", "体重下降", LocalDateTime.now())));

        mockMvc.perform(get("/api/v1/plan/history"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.code").value(200))
                .andExpect(jsonPath("$.data[0].id").value(1));
    }

    @Test
    void getDetail_shouldReturn200() throws Exception {
        when(planService.getDetail(1L, "USER", 1L)).thenReturn(detailResponse);

        mockMvc.perform(get("/api/v1/plan/1"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.code").value(200))
                .andExpect(jsonPath("$.data.planType").value("COMBINED"));
    }

    @Test
    void getGenerateCount_shouldReturn200() throws Exception {
        when(planService.getGenerateCount(1L, "USER"))
                .thenReturn(new GenerateCountResponse(1, 2, 1));

        mockMvc.perform(get("/api/v1/plan/generate-count"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.code").value(200))
                .andExpect(jsonPath("$.data.remaining").value(1));
    }
}
