// @generated by AI
package com.smarthealth.controller;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.smarthealth.dto.request.AddWeightRequest;
import com.smarthealth.dto.response.WeightRecordResponse;
import com.smarthealth.dto.response.WeightTrendResponse;
import com.smarthealth.security.JwtAuthenticationFilter;
import com.smarthealth.security.JwtTokenProvider;
import com.smarthealth.security.UserPrincipal;
import com.smarthealth.service.WeightService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.http.MediaType;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.test.web.servlet.MockMvc;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.util.List;

import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@WebMvcTest(controllers = WeightController.class)
@AutoConfigureMockMvc(addFilters = false)
class WeightControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private ObjectMapper objectMapper;

    @MockBean
    private WeightService weightService;

    @MockBean
    private JwtTokenProvider jwtTokenProvider;

    @MockBean
    private JwtAuthenticationFilter jwtAuthenticationFilter;

    @BeforeEach
    void setUp() {
        UserPrincipal principal = new UserPrincipal(1L, "testuser", "USER");
        SecurityContextHolder.getContext().setAuthentication(
                new UsernamePasswordAuthenticationToken(principal, null,
                        List.of(new SimpleGrantedAuthority("ROLE_USER"))));
    }

    @Test
    void addWeight_shouldReturn200() throws Exception {
        AddWeightRequest request = new AddWeightRequest();
        request.setWeight(BigDecimal.valueOf(79.5));
        request.setRecordDate(LocalDate.of(2026, 6, 8));

        mockMvc.perform(post("/api/v1/weight/add")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.code").value(200));
    }

    @Test
    void getHistory_shouldReturn200() throws Exception {
        when(weightService.getHistory(1L))
                .thenReturn(List.of(
                        new WeightRecordResponse(1L, BigDecimal.valueOf(80.0), LocalDate.of(2026, 6, 1))));

        mockMvc.perform(get("/api/v1/weight/history"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.code").value(200))
                .andExpect(jsonPath("$.data[0].weight").value(80.0));
    }

    @Test
    void deleteWeight_shouldReturn200() throws Exception {
        mockMvc.perform(delete("/api/v1/weight/1"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.code").value(200));
    }

    @Test
    void getTrend_shouldReturn200_withDefaultWeek() throws Exception {
        when(weightService.getTrend(1L, "week"))
                .thenReturn(new WeightTrendResponse(
                        List.of("06-01", "06-08"),
                        List.of(BigDecimal.valueOf(80.0), BigDecimal.valueOf(79.5))));

        mockMvc.perform(get("/api/v1/weight/trend"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.code").value(200))
                .andExpect(jsonPath("$.data.dates[0]").value("06-01"))
                .andExpect(jsonPath("$.data.values[0]").value(80.0));
    }

    @Test
    void getTrend_shouldReturn200_withMonthParam() throws Exception {
        when(weightService.getTrend(1L, "month"))
                .thenReturn(new WeightTrendResponse(List.of(), List.of()));

        mockMvc.perform(get("/api/v1/weight/trend?period=month"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.code").value(200));
    }
}
