// @generated by AI
package com.smarthealth.controller;

import com.smarthealth.common.Result;
import com.smarthealth.dto.request.AiConfigRequest;
import com.smarthealth.dto.response.AiConfigResponse;
import com.smarthealth.security.UserPrincipal;
import com.smarthealth.service.UserAiConfigService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.*;

@Tag(name = "AI 配置", description = "用户自定义 AI API Key、本地模型切换")
@RestController
@RequestMapping("/api/v1/ai-config")
@RequiredArgsConstructor
public class AiConfigController {

    private final UserAiConfigService userAiConfigService;

    @Operation(summary = "获取我的 AI 配置")
    @GetMapping
    @PreAuthorize("isAuthenticated()")
    public Result<AiConfigResponse> getConfig(@AuthenticationPrincipal UserPrincipal principal) {
        return Result.success(userAiConfigService.getConfig(principal.getUserId()));
    }

    @Operation(summary = "保存 AI 配置（自动测试连接）")
    @PostMapping
    @PreAuthorize("isAuthenticated()")
    public Result<AiConfigResponse> saveConfig(@AuthenticationPrincipal UserPrincipal principal,
                                                @Valid @RequestBody AiConfigRequest request) {
        AiConfigResponse response = userAiConfigService.saveConfig(principal.getUserId(), request);
        return Result.success("配置保存成功", response);
    }

    @Operation(summary = "重置 AI 配置为默认")
    @DeleteMapping
    @PreAuthorize("isAuthenticated()")
    public Result<Void> deleteConfig(@AuthenticationPrincipal UserPrincipal principal) {
        userAiConfigService.deleteConfig(principal.getUserId());
        return Result.success("已重置为默认配置", null);
    }
}
