// @generated by AI
package com.smarthealth.controller;

import com.smarthealth.common.Result;
import com.smarthealth.dto.request.ChatRequest;
import com.smarthealth.dto.response.ChatResponse;
import com.smarthealth.security.UserPrincipal;
import com.smarthealth.service.ChatService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.*;

@Tag(name = "智能问答", description = "VIP 智能健康问答")
@RestController
@RequestMapping("/api/v1/chat")
@RequiredArgsConstructor
public class ChatController {

    private final ChatService chatService;

    @Operation(summary = "VIP 智能问答")
    @PostMapping("/ask")
    @PreAuthorize("hasRole('VIP')")
    public Result<ChatResponse> askQuestion(@AuthenticationPrincipal UserPrincipal principal,
                                             @Valid @RequestBody ChatRequest request) {
        return Result.success(chatService.askQuestion(principal.getUserId(), principal.getRole(), request));
    }
}
