// @generated by AI
package com.smarthealth.controller;

import com.smarthealth.common.Result;
import com.smarthealth.dto.response.HealthResponse;
import com.smarthealth.service.HealthService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.RequiredArgsConstructor;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RestController;

@Tag(name = "健康检查", description = "系统健康状态检查")
@RestController
@RequiredArgsConstructor
public class HealthController {

    private final HealthService healthService;

    @Operation(summary = "系统健康检查")
    @GetMapping("/api/v1/health")
    public Result<HealthResponse> health() {
        return Result.success(healthService.check());
    }
}
