// @generated by AI
package com.smarthealth.controller;

import com.smarthealth.common.Result;
import com.smarthealth.dto.response.GenerateCountResponse;
import com.smarthealth.dto.response.PlanDetailResponse;
import com.smarthealth.dto.response.PlanHistoryResponse;
import com.smarthealth.security.UserPrincipal;
import com.smarthealth.service.PlanService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import lombok.RequiredArgsConstructor;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.*;

import java.util.List;

@Tag(name = "AI 计划", description = "AI 饮食与运动计划生成")
@RestController
@RequestMapping("/api/v1/plan")
@RequiredArgsConstructor
public class PlanController {

    private final PlanService planService;

    @Operation(summary = "生成 AI 计划")
    @PostMapping("/generate")
    public Result<PlanDetailResponse> generatePlan(@AuthenticationPrincipal UserPrincipal principal) {
        PlanDetailResponse response = planService.generatePlan(principal.getUserId(), principal.getRole());
        return Result.success("生成成功", response);
    }

    @Operation(summary = "查询历史计划")
    @GetMapping("/history")
    public Result<List<PlanHistoryResponse>> getHistory(@AuthenticationPrincipal UserPrincipal principal) {
        return Result.success(planService.getHistory(principal.getUserId()));
    }

    @Operation(summary = "查询计划详情")
    @GetMapping("/{id}")
    public Result<PlanDetailResponse> getDetail(@AuthenticationPrincipal UserPrincipal principal,
                                                 @PathVariable Long id) {
        return Result.success(planService.getDetail(principal.getUserId(), principal.getRole(), id));
    }

    @Operation(summary = "查询今日生成次数")
    @GetMapping("/generate-count")
    public Result<GenerateCountResponse> getGenerateCount(@AuthenticationPrincipal UserPrincipal principal) {
        return Result.success(planService.getGenerateCount(principal.getUserId(), principal.getRole()));
    }
}
