// @generated by AI
package com.smarthealth.controller;

import com.smarthealth.common.Result;
import com.smarthealth.dto.request.SaveProfileRequest;
import com.smarthealth.dto.response.ProfileResponse;
import com.smarthealth.security.UserPrincipal;
import com.smarthealth.service.ProfileService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.*;

@Tag(name = "健康档案", description = "用户健康档案管理")
@RestController
@RequestMapping("/api/v1/profile")
@RequiredArgsConstructor
public class ProfileController {

    private final ProfileService profileService;

    @Operation(summary = "查询健康档案")
    @GetMapping
    public Result<ProfileResponse> getProfile(@AuthenticationPrincipal UserPrincipal principal) {
        return Result.success(profileService.getProfile(principal.getUserId()));
    }

    @Operation(summary = "保存健康档案")
    @PostMapping
    public Result<Void> saveProfile(@AuthenticationPrincipal UserPrincipal principal,
                                     @Valid @RequestBody SaveProfileRequest request) {
        profileService.saveProfile(principal.getUserId(), request);
        return Result.success("保存成功", null);
    }

    @Operation(summary = "修改健康档案")
    @PutMapping
    public Result<Void> updateProfile(@AuthenticationPrincipal UserPrincipal principal,
                                       @Valid @RequestBody SaveProfileRequest request) {
        profileService.updateProfile(principal.getUserId(), request);
        return Result.success("修改成功", null);
    }
}
