// @generated by AI
package com.smarthealth.controller;

import com.smarthealth.common.Result;
import com.smarthealth.dto.request.AddWeightRequest;
import com.smarthealth.dto.response.WeightRecordResponse;
import com.smarthealth.security.UserPrincipal;
import com.smarthealth.service.WeightService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.*;
import java.util.List;

@Tag(name = "体重记录", description = "用户体重记录管理")
@RestController
@RequestMapping("/api/v1/weight")
@RequiredArgsConstructor
public class WeightController {

    private final WeightService weightService;

    @Operation(summary = "添加体重记录")
    @PostMapping("/add")
    public Result<Void> addWeight(@AuthenticationPrincipal UserPrincipal principal,
                                   @Valid @RequestBody AddWeightRequest request) {
        weightService.addWeight(principal.getUserId(), request);
        return Result.success("添加成功", null);
    }

    @Operation(summary = "查询体重历史")
    @GetMapping("/history")
    public Result<List<WeightRecordResponse>> getHistory(@AuthenticationPrincipal UserPrincipal principal) {
        return Result.success(weightService.getHistory(principal.getUserId()));
    }

    @Operation(summary = "删除体重记录")
    @DeleteMapping("/{id}")
    public Result<Void> deleteWeight(@AuthenticationPrincipal UserPrincipal principal,
                                      @PathVariable Long id) {
        weightService.deleteWeight(principal.getUserId(), id);
        return Result.success("删除成功", null);
    }
}
