-- @generated by AI
-- User AI configuration: custom API key, local model preference
CREATE TABLE user_ai_config (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    user_id BIGINT NOT NULL UNIQUE,
    provider VARCHAR(20) NOT NULL DEFAULT 'DEFAULT' COMMENT 'DEFAULT / CUSTOM / LOCAL',
    api_key VARCHAR(500) COMMENT '用户自定义 API Key',
    api_url VARCHAR(500) COMMENT '自定义 API 地址',
    model VARCHAR(100) COMMENT '模型名称',
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    FOREIGN KEY (user_id) REFERENCES `user`(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户 AI 配置';
