// @generated by AI
package com.smarthealth.mapper;

import com.smarthealth.entity.UserAiConfig;
import org.apache.ibatis.annotations.Mapper;

@Mapper
public interface UserAiConfigMapper {
    UserAiConfig findByUserId(Long userId);
    void insert(UserAiConfig config);
    void update(UserAiConfig config);
    void deleteByUserId(Long userId);
}
