// @generated by AI
package com.smarthealth.controller.admin;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.smarthealth.dto.response.PlanHistoryResponse;
import com.smarthealth.dto.response.WeightRecordResponse;
import com.smarthealth.entity.User;
import com.smarthealth.mapper.UserMapper;
import com.smarthealth.config.SecurityConfig;
import com.smarthealth.security.JwtAuthenticationFilter;
import com.smarthealth.security.JwtTokenProvider;
import com.smarthealth.security.UserPrincipal;
import com.smarthealth.service.PlanService;
import com.smarthealth.service.ProfileService;
import com.smarthealth.service.WeightService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.context.annotation.Import;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.test.web.servlet.MockMvc;

import java.math.BigDecimal;
import java.time.LocalDate;
import java.time.LocalDateTime;
import java.util.List;

import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.when;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@WebMvcTest(controllers = AdminUserController.class)
@AutoConfigureMockMvc(addFilters = false)
@Import(SecurityConfig.class)
class AdminUserControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private ObjectMapper objectMapper;

    @MockBean
    private UserMapper userMapper;

    @MockBean
    private WeightService weightService;

    @MockBean
    private PlanService planService;

    @MockBean
    private ProfileService profileService;

    @MockBean
    private JwtTokenProvider jwtTokenProvider;

    @MockBean
    private JwtAuthenticationFilter jwtAuthenticationFilter;

    @BeforeEach
    void setUp() {
        UserPrincipal principal = new UserPrincipal(1L, "admin", "ADMIN");
        SecurityContextHolder.getContext().setAuthentication(
                new UsernamePasswordAuthenticationToken(principal, null,
                        List.of(new SimpleGrantedAuthority("ROLE_ADMIN"))));
    }

    @Test
    void listUsers_shouldReturn200() throws Exception {
        User testUser = new User();
        testUser.setId(1L);
        testUser.setUsername("testuser");
        testUser.setRole("USER");
        testUser.setStatus(1);
        testUser.setCreateTime(LocalDateTime.of(2026, 6, 8, 10, 0, 0));

        when(userMapper.findByPage(null, 0, 10)).thenReturn(List.of(testUser));
        when(userMapper.countByKeyword(null)).thenReturn(1L);

        mockMvc.perform(get("/api/v1/admin/users"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.code").value(200))
                .andExpect(jsonPath("$.data.total").value(1))
                .andExpect(jsonPath("$.data.records[0].id").value(1))
                .andExpect(jsonPath("$.data.records[0].createTime").exists());
    }

    @Test
    void getUserDetail_shouldReturn200() throws Exception {
        User testUser = new User();
        testUser.setId(1L);
        testUser.setUsername("testuser");
        testUser.setRole("USER");
        testUser.setStatus(1);

        when(userMapper.findById(1L)).thenReturn(testUser);

        mockMvc.perform(get("/api/v1/admin/users/1"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.code").value(200))
                .andExpect(jsonPath("$.data.id").value(1))
                .andExpect(jsonPath("$.data.username").value("testuser"));
    }

    @Test
    void getUserDetail_shouldReturn404_whenNotFound() throws Exception {
        when(userMapper.findById(99L)).thenReturn(null);

        mockMvc.perform(get("/api/v1/admin/users/99"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.code").value(404));
    }

    @Test
    void enableUser_shouldReturn200() throws Exception {
        mockMvc.perform(put("/api/v1/admin/users/1/enable"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.code").value(200));
    }

    @Test
    void disableUser_shouldReturn200() throws Exception {
        mockMvc.perform(put("/api/v1/admin/users/1/disable"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.code").value(200));
    }

    @Test
    void getUserWeights_shouldReturn200() throws Exception {
        when(weightService.getHistory(1L))
                .thenReturn(List.of(
                        new WeightRecordResponse(1L, BigDecimal.valueOf(80.0), LocalDate.of(2026, 6, 1))));

        mockMvc.perform(get("/api/v1/admin/users/1/weights"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.code").value(200))
                .andExpect(jsonPath("$.data[0].weight").value(80.0));
    }

    @Test
    void getUserPlans_shouldReturn200() throws Exception {
        when(planService.getHistory(1L))
                .thenReturn(List.of(
                        new PlanHistoryResponse(1L, "COMBINED", "BASIC", "体重下降", LocalDateTime.now())));

        mockMvc.perform(get("/api/v1/admin/users/1/plans"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.code").value(200))
                .andExpect(jsonPath("$.data[0].planType").value("COMBINED"));
    }

    @Test
    void getUserProfile_shouldReturn200() throws Exception {
        var profile = new com.smarthealth.dto.response.ProfileResponse(
                1L, 22, "男", BigDecimal.valueOf(175), BigDecimal.valueOf(80),
                "较低", "少油少糖", "减脂");
        when(profileService.getProfile(1L)).thenReturn(profile);

        mockMvc.perform(get("/api/v1/admin/users/1/profile"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.code").value(200))
                .andExpect(jsonPath("$.data.age").value(22));
    }

    @Test
    void deleteWeightRecord_shouldReturn200() throws Exception {
        mockMvc.perform(delete("/api/v1/admin/users/weights/1"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.code").value(200));
    }

    @Test
    void deletePlanRecord_shouldReturn200() throws Exception {
        mockMvc.perform(delete("/api/v1/admin/users/plans/1"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.code").value(200));
    }
}
