// @generated by AI
package com.smarthealth.controller.admin;

import com.fasterxml.jackson.databind.ObjectMapper;
import com.smarthealth.dto.request.CreateKnowledgeRequest;
import com.smarthealth.config.SecurityConfig;
import com.smarthealth.security.JwtAuthenticationFilter;
import com.smarthealth.security.JwtTokenProvider;
import com.smarthealth.security.UserPrincipal;
import com.smarthealth.service.RagService;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.web.servlet.AutoConfigureMockMvc;
import org.springframework.boot.test.autoconfigure.web.servlet.WebMvcTest;
import org.springframework.boot.test.mock.mockito.MockBean;
import org.springframework.context.annotation.Import;
import org.springframework.http.MediaType;
import org.springframework.security.authentication.UsernamePasswordAuthenticationToken;
import org.springframework.security.core.authority.SimpleGrantedAuthority;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.test.web.servlet.MockMvc;

import java.util.List;
import java.util.Map;

import static org.mockito.ArgumentMatchers.*;
import static org.mockito.Mockito.*;
import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*;
import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;

@WebMvcTest(controllers = KnowledgeController.class)
@AutoConfigureMockMvc(addFilters = false)
@Import(SecurityConfig.class)
class KnowledgeControllerTest {

    @Autowired
    private MockMvc mockMvc;

    @Autowired
    private ObjectMapper objectMapper;

    @MockBean
    private RagService ragService;

    @MockBean
    private JwtTokenProvider jwtTokenProvider;

    @MockBean
    private JwtAuthenticationFilter jwtAuthenticationFilter;

    @BeforeEach
    void setUp() {
        UserPrincipal principal = new UserPrincipal(1L, "admin", "ADMIN");
        SecurityContextHolder.getContext().setAuthentication(
                new UsernamePasswordAuthenticationToken(principal, null,
                        List.of(new SimpleGrantedAuthority("ROLE_ADMIN"))));
    }

    @Test
    void createKnowledge_shouldReturn200() throws Exception {
        CreateKnowledgeRequest request = new CreateKnowledgeRequest();
        request.setDocument("减脂期间应控制总热量摄入");
        CreateKnowledgeRequest.Metadata metadata = new CreateKnowledgeRequest.Metadata();
        metadata.setCategory("饮食");
        metadata.setTitle("减脂原则");
        metadata.setStatus("enabled");
        metadata.setLevel("all");
        request.setMetadata(metadata);

        when(ragService.addKnowledge(anyString(), anyMap())).thenReturn("knowledge_test_id");

        mockMvc.perform(post("/api/v1/admin/knowledge")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.code").value(200))
                .andExpect(jsonPath("$.data.knowledgeId").value("knowledge_test_id"));
    }

    @Test
    void updateKnowledge_shouldReturn200() throws Exception {
        CreateKnowledgeRequest request = new CreateKnowledgeRequest();
        request.setDocument("更新后的知识内容");
        CreateKnowledgeRequest.Metadata metadata = new CreateKnowledgeRequest.Metadata();
        metadata.setCategory("运动");
        metadata.setTitle("运动建议");
        metadata.setStatus("enabled");
        metadata.setLevel("all");
        request.setMetadata(metadata);

        mockMvc.perform(put("/api/v1/admin/knowledge/test-id-123")
                        .contentType(MediaType.APPLICATION_JSON)
                        .content(objectMapper.writeValueAsString(request)))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.code").value(200));
    }

    @Test
    void deleteKnowledge_shouldReturn200() throws Exception {
        mockMvc.perform(delete("/api/v1/admin/knowledge/test-id-123"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.code").value(200));
    }

    @Test
    void listKnowledge_shouldReturn200() throws Exception {
        when(ragService.listKnowledge(any(), any(), any(), any())).thenReturn(List.of(
                Map.of("id", "id1", "document", "知识1", "metadata", Map.of("category", "饮食"))));

        mockMvc.perform(get("/api/v1/admin/knowledge/list"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.code").value(200))
                .andExpect(jsonPath("$.data[0].id").value("id1"));
    }

    @Test
    void listKnowledge_shouldFilterByCategory() throws Exception {
        when(ragService.listKnowledge(eq("饮食"), any(), any(), any())).thenReturn(List.of(
                Map.of("id", "id2", "document", "饮食知识", "metadata", Map.of("category", "饮食"))));

        mockMvc.perform(get("/api/v1/admin/knowledge/list?category=饮食"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.code").value(200))
                .andExpect(jsonPath("$.data[0].id").value("id2"));
    }

    @Test
    void listKnowledge_shouldFilterByStatus() throws Exception {
        when(ragService.listKnowledge(any(), any(), eq("disabled"), any())).thenReturn(List.of());

        mockMvc.perform(get("/api/v1/admin/knowledge/list?status=disabled"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.code").value(200));
    }

    @Test
    void enableKnowledge_shouldReturn200() throws Exception {
        mockMvc.perform(put("/api/v1/admin/knowledge/test-id/enable"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.code").value(200));
    }

    @Test
    void disableKnowledge_shouldReturn200() throws Exception {
        mockMvc.perform(put("/api/v1/admin/knowledge/test-id/disable"))
                .andExpect(status().isOk())
                .andExpect(jsonPath("$.code").value(200));
    }

    @Test
    void shouldReturn403_whenUserRole() throws Exception {
        SecurityContextHolder.getContext().setAuthentication(
                new UsernamePasswordAuthenticationToken(
                        new UserPrincipal(2L, "normaluser", "USER"), null,
                        List.of(new SimpleGrantedAuthority("ROLE_USER"))));

        mockMvc.perform(get("/api/v1/admin/knowledge/list"))
                .andExpect(status().isForbidden())
                .andExpect(jsonPath("$.code").value(403));
    }
}
